/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type Auth struct {

	// Virtual server traffic Authentication profile configuration
	Profile string `json:"profile,omitempty"`

	// Online Certificate System Protocol (OCSP) responder configuration
	OcspResponder string `json:"ocspResponder,omitempty"`

	// Kerberos configuration for remote client authentication
	KerberosDelegation string `json:"kerberosDelegation,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// RADIUS server configuration for use with RADIUS authentication profiles
	RadiusServer string `json:"radiusServer,omitempty"`

	// TACACS+ configuration for remote TACACS+ client authentication
	Tacacs string `json:"tacacs,omitempty"`

	// LDAP configuration for remote LDAP client authentication
	Ldap string `json:"ldap,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Certificate Revocation List Distribution Point (CRDLP) server configuration, for use with a CRLDP authentication profile
	CrldpServer string `json:"crldpServer,omitempty"`

	// RADIUS configuration for remote RADIUS client authentication
	Radius string `json:"radius,omitempty"`

	// SSL client certificate configuration, for use with remote SSL-based LDAP authorization
	SslCcLdap string `json:"sslCcLdap,omitempty"`

	// SSL client certificate configuration, for use with remote SSL-based CRLDP authorization
	SslCrldp string `json:"sslCrldp,omitempty"`

	// OCSP configuration for implementing remote OCSP-based client authentication
	SslOcsp string `json:"sslOcsp,omitempty"`
}
