/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type DnsCacheRecordsNameserver struct {

	// Chassis slot to query.
	Slot int64 `json:"slot,omitempty"`

	// Include or exclude nameservers which are EDNS lame.
	HasEdns string `json:"hasEdns,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Name of DNS Cache configuration object to inspect.
	Cache string `json:"cache,omitempty"`

	// Filter results by TTL, low:high.
	TtlRange string `json:"ttlRange,omitempty"`

	// Filter results by nameserver address.
	Address string `json:"address,omitempty"`

	// Filter results by RTT, low:high.
	RttRange string `json:"rttRange,omitempty"`

	// Include or exclude records which have lame zones.
	HasLame string `json:"hasLame,omitempty"`

	// TMM to query (typically unset and used for debugging).
	Tmm int64 `json:"tmm,omitempty"`

	// Filter results by zone name.
	ZoneName string `json:"zoneName,omitempty"`
}
