/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type EvictionPolicy struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// The target maximum load as a percentage (of the full capacity available to the context assigned).
	HighWater int64 `json:"highWater,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// The percentage (of the full capacity available to the context assigned) at which aggressive killing of flows is enabled or disabled.
	LowWater int64 `json:"lowWater,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
