/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileNtlm struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the name of the NTLM persistence cookie to be inserted.
	InsertCookieName string `json:"insertCookieName,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// The cookie that will be used if \"key-by-cookie\" is enabled.
	KeyByCookieName string `json:"keyByCookieName,omitempty"`

	// Enable or disable OneConnect keying by client IP address. The default is disabled.
	KeyByIpAddress string `json:"keyByIpAddress,omitempty"`

	// Enable or disable OneConnect keying by NTLM domain. The default is disabled.
	KeyByDomain string `json:"keyByDomain,omitempty"`

	// Enable or disable OneConnect keying by NTLM target. The default is disabled.
	KeyByTarget string `json:"keyByTarget,omitempty"`

	// Specifies an optional domain for the inserted cookie. The default is \"none\", which causes no domain to be configured for the inserted cookie.
	InsertCookieDomain string `json:"insertCookieDomain,omitempty"`

	// Enable or disable OneConnect keying by cookie. The default is disabled.
	KeyByCookie string `json:"keyByCookie,omitempty"`

	// Enable or disable OneConnect keying by NTLM user. The default is enabled.
	KeyByUser string `json:"keyByUser,omitempty"`

	// Specifies the pass phrase for the inserted persistence cookie.
	InsertCookiePassphrase string `json:"insertCookiePassphrase,omitempty"`

	// Enable or disable OneConnect keying by NTLM workstation. The default is disabled.
	KeyByWorkstation string `json:"keyByWorkstation,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
