/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileAnalytics struct {

	// Specifies which email addresses receive alerts by email when notification-by-email is enabled.
	NotificationEmailAddresses string `json:"notificationEmailAddresses,omitempty"`

	// Enables or disables the collection of the page load time statistics.
	CollectPageLoadTime string `json:"collectPageLoadTime,omitempty"`

	// Enables or disables sending the analytics alerts by SNMP traps (notification-by-syslog must be enabled).
	NotificationBySnmp string `json:"notificationBySnmp,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Enables or disables the internal logging of captured traffic.
	CapturedTrafficInternalLogging string `json:"capturedTrafficInternalLogging,omitempty"`

	// Enables or disables the collection of HTTP response codes returned by the servers.
	CollectResponseCodes string `json:"collectResponseCodes,omitempty"`

	// Enables or disables the collection of server latency statistics. Deprecated: server latency is always collected.
	CollectServerLatency string `json:"collectServerLatency,omitempty"`

	// Enables or disables the external logging of captured traffic.
	CapturedTrafficExternalLogging string `json:"capturedTrafficExternalLogging,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// Enables or disables the collection of HTTP methods statistics.
	CollectMethods string `json:"collectMethods,omitempty"`

	SessionTimeout int64 `json:"sessionTimeout,omitempty"`

	// Enables or disables the collection of client IPs statistics.
	CollectIp string `json:"collectIp,omitempty"`

	// Enables or disables the collection of the names of the countries from where the traffic was sent.
	CollectGeo string `json:"collectGeo,omitempty"`

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Specifies the number of minutes of user non-activity before the system considers the session to be over.
	SessionTimeoutMinutes string `json:"sessionTimeoutMinutes,omitempty"`

	// Enables or disables publishing analytics statistics for iRules.
	PublishIruleStatistics string `json:"publishIruleStatistics,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the external logging publisher used to send statistical data to one or more destinations.
	ExternalLoggingPublisher string `json:"externalLoggingPublisher,omitempty"`

	// Enables or disables the external logging of the collected statistics.
	CollectedStatsExternalLogging string `json:"collectedStatsExternalLogging,omitempty"`

	// Enables or disables logging of the analytics alerts into the Syslog.
	NotificationBySyslog string `json:"notificationBySyslog,omitempty"`

	// Enables or disables the collection of maximum TPS and throughput for all collected entities.
	CollectMaxTpsAndThroughput string `json:"collectMaxTpsAndThroughput,omitempty"`

	// The SMTP configuration to be used with analytics
	SmtpConfig string `json:"smtpConfig,omitempty"`

	// Enables or disables transaction sampling. This attribute can be set in the default profile only.
	Sampling string `json:"sampling,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Enables or disables the collection of URL statistics.
	CollectUrl string `json:"collectUrl,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Enables or disables the collection of client side subnets.
	CollectSubnets string `json:"collectSubnets,omitempty"`

	SamplingRatio int64 `json:"samplingRatio,omitempty"`

	// Enables or disables the collection of user sessions.
	CollectUserSessions string `json:"collectUserSessions,omitempty"`

	// Enables or disables sending the analytics alerts by email.
	NotificationByEmail string `json:"notificationByEmail,omitempty"`

	// Enables or disables the collection of user agents statistics.
	CollectUserAgent string `json:"collectUserAgent,omitempty"`

	// Enables or disables the collection of throughput statistics. Deprecated: HTTP throughput is always collected.
	CollectHttpThroughput string `json:"collectHttpThroughput,omitempty"`

	// Enables or disables the internal logging of the collected statistics.
	CollectedStatsInternalLogging string `json:"collectedStatsInternalLogging,omitempty"`

	// Specifies the condition for adding a secure attribute to the session cookie. The default value is ssl-only.
	SessionCookieSecurity string `json:"sessionCookieSecurity,omitempty"`
}
