/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmLsnPoolPcp struct {

	// Specifies the PCP profile used for this LSN pool.
	Profile string `json:"profile,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the DSLITE tunnel used by PCP for this LSN pool.  Clients can send PCP requests through this tunnel.
	Dslite string `json:"dslite,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the PCP Server SelfIP name used for this LSN pool.  Clients send PCP requests to this IP address.
	Selfip string `json:"selfip,omitempty"`
}
