/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmNat struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Enables or disables Address Resolution Protocol (ARP).
	Arp string `json:"arp,omitempty"`

	// Displays the administrative partition within which the nat resides.
	Partition string `json:"partition,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the traffic group for the NAT. The default is inherited from the containing folder.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// Disables the NAT.
	Disabled bool `json:"disabled,omitempty"`

	// Translation/destination IP address. This may not be changed after the nat has been created.
	TranslationAddress string `json:"translationAddress,omitempty"`

	Unit int64 `json:"unit,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the IP address from which traffic is being initiated.
	OriginatingAddress string `json:"originatingAddress,omitempty"`

	// Indicates the NAT is disabled on the list of VLANs.
	VlansDisabled bool `json:"vlansDisabled,omitempty"`

	// Enables the NAT.
	Enabled bool `json:"enabled,omitempty"`

	// Indicates the NAT is enabled on the list of VLANs.
	VlansEnabled bool `json:"vlansEnabled,omitempty"`

	// Specifies whether to automatically map last hop for pools or not. The default is to use next level's default.
	AutoLasthop string `json:"autoLasthop,omitempty"`

	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`
}
