/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileFtp struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Enables the FTP data channel to inherit the TCP profile used by the control channel. If disabled, the data channel uses FastL4 (BigProto) only. The default is unchecked (disabled).
	InheritParentProfile string `json:"inheritParentProfile,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Configures the log publisher that handles events logging for this profile.
	LogPublisher string `json:"logPublisher,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// Configures the ALG log profile that controls logging.
	LogProfile string `json:"logProfile,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// This setting is enabled by default, and thus, automatically translates RFC 2428 extended requests EPSV and EPRT to PASV and PORT when communicating with IPv4 servers.
	TranslateExtended string `json:"translateExtended,omitempty"`

	// Enables secure FTP traffic for the BIG-IP Application Security Manager. You can set the security option only if the system is licensed for the BIG-IP Application Security Manager. The default value is disabled.
	Security string `json:"security,omitempty"`

	// Allow explicit FTPS negotiation. The default is disabled.
	AllowFtps string `json:"allowFtps,omitempty"`

	// Specifies a service for the data channel port used for this FTP profile. The default port is ftp-data.
	Port int64 `json:"port,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
