/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmSnatTranslation struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Indicates whether or not the system responds to ARP requests or sends gratuitous ARPs. The default value is enabled.
	Arp string `json:"arp,omitempty"`

	// Specifies the number of seconds that IP connections initiated using a SNAT address are allowed to remain idle before being automatically disconnected. The default value is indefinite.
	IpIdleTimeout string `json:"ipIdleTimeout,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the number of seconds that TCP connections initiated using a SNAT address are allowed to remain idle before being automatically disconnected. The default value is indefinite.
	TcpIdleTimeout string `json:"tcpIdleTimeout,omitempty"`

	// Specifies the traffic group of the SNAT. The default is inherited from the containing folder.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// Disables SNAT translation on the system.
	Disabled bool `json:"disabled,omitempty"`

	// Specifies the number of seconds that UDP connections initiated using a SNAT address are allowed to remain idle before being automatically disconnected. The default value is indefinite.
	UdpIdleTimeout string `json:"udpIdleTimeout,omitempty"`

	// Specifies the number of connections a translation address must reach before it no longer initiates a connection. The default value of 0 disables this option.
	ConnectionLimit int64 `json:"connectionLimit,omitempty"`

	// The translation IP address.
	Address string `json:"address,omitempty"`

	Unit int64 `json:"unit,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Displays the administrative partition within which the snat resides.
	Partition string `json:"partition,omitempty"`

	// Enables SNAT translation on the system. This is the default setting.
	Enabled bool `json:"enabled,omitempty"`

	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`
}
