/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmMonitorIcmp struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Specifies the size of the sliding window, in seconds, which records probe history.  For example, if this value is 300, then a sliding window of the last five minutes' probe history will be used for calculating probe mean latency.
	AdaptiveSamplingTimespan int64 `json:"adaptiveSamplingTimespan,omitempty"`

	// Displays the administrative partition within which the monitor resides.
	Partition string `json:"partition,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies how often in seconds that the system issues the monitor check when the node is up. The default value is the same as the (down) interval.
	UpInterval int64 `json:"upInterval,omitempty"`

	// Specifies whether the system automatically changes the status of a resource to enabled at the next successful monitor check. The default value is disabled. If you set this option to enabled, you must manually re-enable the resource before the system can use it for load balancing connections.
	ManualResume string `json:"manualResume,omitempty"`

	// Specifies how far from mean latency each monitor probe is allowed to be.  If adaptive-divergence-type is relative, this value is a percentage deviation from mean (e.g. 50 would indicate the probe is allowed to exceed the mean latency by 50%.)  If adaptive-divergence-type is absolute, this value is an offset from mean in milliseconds (e.g. 250 would indicate the probe is allowed allowed to exceed the mean latency by 250 ms.)
	AdaptiveDivergenceValue int64 `json:"adaptiveDivergenceValue,omitempty"`

	// Specifies the existing monitor from which the system imports settings for the new monitor.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the IP address of the resource that is the destination of this monitor. Possible values are: * (Specifies to perform a health check on the IP address of the node),  IP  (Specifies to perform a health check on the IP address that you specify, and mark the associated node up or down as a result of the response.), and  IP  (with the transparent option enabled) (Specifies to perform a health check on the IP address you specify, and route the check through the associated node IP address, and mark the associated node IP address up or down accordingly.).
	Destination string `json:"destination,omitempty"`

	// Specifies the hard limit, in milliseconds, which the probe is not allowed to exceed, regardless of the divergence value.  For example, if this value is 500, then the probe latency may not exceed 500 ms even if that would still fall within the divergence value.
	AdaptiveLimit int64 `json:"adaptiveLimit,omitempty"`

	// Specifies whether the adaptive feature is enabled for this monitor.  Not all monitors support the adaptive feature.
	Adaptive string `json:"adaptive,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the frequency at which the system issues the monitor check. The default value is 5 seconds.
	Interval int64 `json:"interval,omitempty"`

	// Specifies whether the monitor operates in transparent mode. Monitors in transparent mode can monitor pool members through firewalls. The default value is disabled.
	Transparent string `json:"transparent,omitempty"`

	// Specifies the amount of time in seconds after the first successful response before a node will be marked up.  A value of 0 will cause a node to be marked up immediately after a valid  response is received from the node. The default setting is 0.
	TimeUntilUp int64 `json:"timeUntilUp,omitempty"`

	// Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 16 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
	Timeout int64 `json:"timeout,omitempty"`

	// Specifies whether the adaptive-divergence-value is relative or absolute.
	AdaptiveDivergenceType string `json:"adaptiveDivergenceType,omitempty"`
}
