/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmMessageRoutingSipProfileRouter struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the maximum number of bytes contained within pending messages that will be held while waiting for a connection to a peer to be created.
	MaxPendingBytes int64 `json:"maxPendingBytes,omitempty"`

	// Specifies the maximum number of pending messages that will be held while waiting for a connection to a peer to be created.
	MaxPendingMessages int64 `json:"maxPendingMessages,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Enables or disables to specify whether the system, when selecting an outgoing connection to a destination peer, prefers the connection established by the incoming request, rather than other connections.
	UseLocalConnection string `json:"useLocalConnection,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all of the settings and values from the specified parent profile.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the behavior of the routing instance.
	OperationMode string `json:"operationMode,omitempty"`
}
