/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmAuthCrldpServer struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Specifies in which order the system attempts to match the base-dn value to the value of the X509v3 attribute crlDistributionPoints. When enabled, the system matches the base-dn value from left to right, or from the beginning of the DN string, to accommodate dirName strings in certificates such as C=US,ST=WA,L=SEA,OU=F5,CN=xxx. The default value is disabled.
	ReverseDn string `json:"reverseDn,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the LDAP base directory name for certificates that specify the CRL distribution point in directory name format (dirName). Use this option when the value of the X509v3 attribute crlDistributionPoints is of type dirName. In this case, the BIG-IP system attempts to match the value of the crlDistributionPoints attribute to the base-dn value. An example of a base-dn value is cn=lxxx,dc=f5,dc=com.
	BaseDn string `json:"baseDn,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Displays the partition within which the server resides.
	Partition string `json:"partition,omitempty"`

	// Specifies an IP address for the CRLDP server. This option is required.
	Host string `json:"host,omitempty"`

	// Specifies the port for CRLDP authentication traffic. The default port is 389.
	Port int64 `json:"port,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
