/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmPolicyRulesConditions struct {

	// Matches all.
	All bool `json:"all,omitempty"`

	// Matches a specific code.
	Code bool `json:"code,omitempty"`

	// Matches on a specific protocol.
	Protocol bool `json:"protocol,omitempty"`

	// The value matches if it is less than a given value.
	Less bool `json:"less,omitempty"`

	// Matches on text.
	Text bool `json:"text,omitempty"`

	// Matches a major.
	Major bool `json:"major,omitempty"`

	// The condition matches on tcp connections.
	Tcp bool `json:"tcp,omitempty"`

	// Matches on round trip time.
	Rtt bool `json:"rtt,omitempty"`

	Org bool `json:"org,omitempty"`

	SslServerHandshake bool `json:"sslServerHandshake,omitempty"`

	Continent bool `json:"continent,omitempty"`

	Last1min bool `json:"last_1min,omitempty"`

	// This condition matches on basic HTTP authorization.
	HttpBasicAuth bool `json:"httpBasicAuth,omitempty"`

	ServerName bool `json:"serverName,omitempty"`

	BrowserType bool `json:"browserType,omitempty"`

	// Matches on maximum segment size.
	Mss bool `json:"mss,omitempty"`

	Last5mins bool `json:"last_5mins,omitempty"`

	RegionCode bool `json:"regionCode,omitempty"`

	// Matches on bits in a cipher.
	CipherBits bool `json:"cipherBits,omitempty"`

	// This condition matches on an HTTP URI.
	HttpUri bool `json:"httpUri,omitempty"`

	SslExtension bool `json:"sslExtension,omitempty"`

	DeviceMake bool `json:"deviceMake,omitempty"`

	// Matches a scheme.
	Scheme bool `json:"scheme,omitempty"`

	// The value matches on local connections.
	Local bool `json:"local,omitempty"`

	// This condition matches on an HTTP header.
	HttpHeader bool `json:"httpHeader,omitempty"`

	// Matches a minor.
	Minor bool `json:"minor,omitempty"`

	// Matches on a username.
	Username bool `json:"username,omitempty"`

	// The value matches if it is greater than a given value.
	Greater bool `json:"greater,omitempty"`

	Matches bool `json:"matches,omitempty"`

	// Matches on a VLAN id.
	VlanId bool `json:"vlanId,omitempty"`

	CountryName bool `json:"countryName,omitempty"`

	// This condition matches on an http method.
	HttpMethod bool `json:"httpMethod,omitempty"`

	// Matches name.
	TmName string `json:"tmName,omitempty"`

	// The opposite of this condition matches.
	Not bool `json:"not,omitempty"`

	// Matches on a password.
	Password bool `json:"password,omitempty"`

	// The value matches if an item is present.
	Present bool `json:"present,omitempty"`

	// This condition matches on an HTTP version.
	HttpVersion bool `json:"httpVersion,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// The value matches if it is less than or equal to a given value
	LessOrEqual bool `json:"lessOrEqual,omitempty"`

	// The value matched on is case insensitive.
	CaseInsensitive bool `json:"caseInsensitive,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Geoip bool `json:"geoip,omitempty"`

	// This condition matches on an HTTP connection status.
	HttpStatus bool `json:"httpStatus,omitempty"`

	// Matches a value.
	Value bool `json:"value,omitempty"`

	// Matches on a route domain.
	RouteDomain bool `json:"routeDomain,omitempty"`

	// The specified values will be matched on.
	Values string `json:"values,omitempty"`

	// This condition matches on an HTTP cookie.
	HttpCookie bool `json:"httpCookie,omitempty"`

	UnnamedQueryParameter bool `json:"unnamedQueryParameter,omitempty"`

	// Matches on a domain.
	Domain bool `json:"domain,omitempty"`

	CountryCode bool `json:"countryCode,omitempty"`

	// Matches a path segment.
	PathSegment bool `json:"pathSegment,omitempty"`

	// The value matched on is case sensitive.
	CaseSensitive bool `json:"caseSensitive,omitempty"`

	// The value matches if it contains a certain string.
	Contains bool `json:"contains,omitempty"`

	// Matches a port.
	Port bool `json:"port,omitempty"`

	// This condition matches on HTTP set cookie.
	HttpSetCookie bool `json:"httpSetCookie,omitempty"`

	// The specified index is used to match.
	Index int64 `json:"index,omitempty"`

	DeviceModel bool `json:"deviceModel,omitempty"`

	SslServerHello bool `json:"sslServerHello,omitempty"`

	CommonName bool `json:"commonName,omitempty"`

	// Matches on a version.
	Version bool `json:"version,omitempty"`

	// The value matches if it is greater than or equal to a given value
	GreaterOrEqual bool `json:"greaterOrEqual,omitempty"`

	RegionName bool `json:"regionName,omitempty"`

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// The value matches if it starts with a certain string.
	StartsWith bool `json:"startsWith,omitempty"`

	SslClientHello bool `json:"sslClientHello,omitempty"`

	// Matches on a VLAN
	Vlan bool `json:"vlan,omitempty"`

	// Matches a query string.
	QueryString bool `json:"queryString,omitempty"`

	// The value matches if it equals a certain value.
	Equals bool `json:"equals,omitempty"`

	// Matches on an expiry.
	Expiry bool `json:"expiry,omitempty"`

	// Matches a host.
	Host bool `json:"host,omitempty"`

	// Matches on a cipher used.
	Cipher bool `json:"cipher,omitempty"`

	// The value matched on is from the internal side of a connection.
	Internal bool `json:"internal,omitempty"`

	Address bool `json:"address,omitempty"`

	// Matches a URI path.
	Path bool `json:"path,omitempty"`

	CpuUsage bool `json:"cpuUsage,omitempty"`

	Last15secs bool `json:"last_15secs,omitempty"`

	// This policy will match on a response.
	Response bool `json:"response,omitempty"`

	// The condition matches on Client SSL connections.
	ClientSsl bool `json:"clientSsl,omitempty"`

	BrowserVersion bool `json:"browserVersion,omitempty"`

	// The value matches on remote conditions.
	Remote bool `json:"remote,omitempty"`

	// Matches an extension.
	Extension bool `json:"extension,omitempty"`

	SslCert bool `json:"sslCert,omitempty"`

	UserAgentToken bool `json:"userAgentToken,omitempty"`

	Isp bool `json:"isp,omitempty"`

	// This policy will match on a request.
	Request bool `json:"request,omitempty"`

	// The value matches if it ends with a certain string.
	EndsWith bool `json:"endsWith,omitempty"`

	// This condition matches on an HTTP host.
	HttpHost bool `json:"httpHost,omitempty"`

	// Matches a query parameter.
	QueryParameter bool `json:"queryParameter,omitempty"`

	// This condition matches on and HTTP referer.
	HttpReferer bool `json:"httpReferer,omitempty"`

	HttpUserAgent bool `json:"httpUserAgent,omitempty"`

	// The value matches if a value is missing.
	Missing bool `json:"missing,omitempty"`

	// The value matched on is from the external side of a connection.
	External bool `json:"external,omitempty"`
}
