/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileStatistics struct {

	// Specifies the profile that you want to use as the parent profile.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Custom field identifier.
	Field8 string `json:"field8,omitempty"`

	// Custom field identifier.
	Field9 string `json:"field9,omitempty"`

	// Custom field identifier.
	Field2 string `json:"field2,omitempty"`

	// Custom field identifier.
	Field3 string `json:"field3,omitempty"`

	// Custom field identifier.
	Field1 string `json:"field1,omitempty"`

	// Custom field identifier.
	Field6 string `json:"field6,omitempty"`

	// Custom field identifier.
	Field7 string `json:"field7,omitempty"`

	// Custom field identifier.
	Field4 string `json:"field4,omitempty"`

	// Custom field identifier.
	Field5 string `json:"field5,omitempty"`

	// Custom field identifier.
	Field29 string `json:"field29,omitempty"`

	// Custom field identifier.
	Field28 string `json:"field28,omitempty"`

	// Custom field identifier.
	Field25 string `json:"field25,omitempty"`

	// Custom field identifier.
	Field24 string `json:"field24,omitempty"`

	// Custom field identifier.
	Field27 string `json:"field27,omitempty"`

	// Custom field identifier.
	Field26 string `json:"field26,omitempty"`

	// Custom field identifier.
	Field21 string `json:"field21,omitempty"`

	// Custom field identifier.
	Field20 string `json:"field20,omitempty"`

	// Custom field identifier.
	Field23 string `json:"field23,omitempty"`

	// Custom field identifier.
	Field22 string `json:"field22,omitempty"`

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Custom field identifier.
	Field18 string `json:"field18,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// Custom field identifier.
	Field10 string `json:"field10,omitempty"`

	// Custom field identifier.
	Field11 string `json:"field11,omitempty"`

	// Custom field identifier.
	Field12 string `json:"field12,omitempty"`

	// Custom field identifier.
	Field13 string `json:"field13,omitempty"`

	// Custom field identifier.
	Field14 string `json:"field14,omitempty"`

	// Custom field identifier.
	Field15 string `json:"field15,omitempty"`

	// Custom field identifier.
	Field16 string `json:"field16,omitempty"`

	// Custom field identifier.
	Field17 string `json:"field17,omitempty"`

	// Custom field identifier.
	Field32 string `json:"field32,omitempty"`

	// Custom field identifier.
	Field19 string `json:"field19,omitempty"`

	// Custom field identifier.
	Field30 string `json:"field30,omitempty"`

	// Custom field identifier.
	Field31 string `json:"field31,omitempty"`
}
