/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmPersistenceCookie struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Specifies a passphrase to be used for cookie encryption.
	CookieEncryptionPassphrase string `json:"cookieEncryptionPassphrase,omitempty"`

	// Specifies whether the secure attribute should be enabled or disabled for the inserted cookies. The default value is enabled.
	Secure string `json:"secure,omitempty"`

	// Specifies, when enabled, that the pool member connection limits are not enforced for persisted clients. Per-virtual connection limits remain hard limits and are not disabled. The default value is disabled.
	OverrideConnectionLimit string `json:"overrideConnectionLimit,omitempty"`

	// Specifies, when enabled, that all persistent connections from a client IP address, which go to the same virtual IP address, also go to the same node. The default value is disabled.
	MatchAcrossServices string `json:"matchAcrossServices,omitempty"`

	// Specifies a unique name for the profile.
	CookieName string `json:"cookieName,omitempty"`

	// Specifies the existing profile from which the system imports settings for the new profile.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies whether the system mirrors persistence records to the high-availability peer. This option is applicable only when the value of the method option is hash. The default value is disabled.
	Mirror string `json:"mirror,omitempty"`

	// Specifies, when enabled, that the cookie persistence entry will be sent to the client on every response, rather than only on the first response.  The default value is disabled.
	AlwaysSend string `json:"alwaysSend,omitempty"`

	// Specifies the cookie hash length. The length is the number of bytes to use when calculating the hash value. The default value is 0 bytes.
	HashLength int64 `json:"hashLength,omitempty"`

	// Specifies, when enabled, that the system can use any pool that contains this persistence record. The default value is disabled.
	MatchAcrossPools string `json:"matchAcrossPools,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the way in which cookie format will be used: \"disabled\": generate old format,unencrypted, \"preferred\": generate encrypted cookie but accept both encrypted and old format, and \"required\": cookie format must be encrypted. Default is required.
	CookieEncryption string `json:"cookieEncryption,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Displays the administrative partition within which the profile resides.
	Partition string `json:"partition,omitempty"`

	// Specifies, when enabled, that all persistent connections from the same client IP address go to the same node. The default value is disabled.
	MatchAcrossVirtuals string `json:"matchAcrossVirtuals,omitempty"`

	Mode string `json:"mode,omitempty"`

	// Specifies the duration of the persistence entries. The default value is 180 seconds.
	Timeout string `json:"timeout,omitempty"`

	// Specifies the cookie hash offset. The offset is the number of bytes in the cookie to skip before calculating the hash value. The default value is 0 bytes.
	HashOffset int64 `json:"hashOffset,omitempty"`

	// Specifies the type of cookie processing that the system uses. The default value is insert.
	Method string `json:"method,omitempty"`

	// Specifies whether the httponly attribute should be enabled or disabled for the inserted cookies. The default value is enabled.
	Httponly string `json:"httponly,omitempty"`

	// Specifies the cookie expiration date in the format d:h:m:s, h:m:s, m:s or seconds. Hours 0-23, minutes 0-59, seconds 0-59. The time period must be less than 24856 days. You can use \"session-cookie\" (0 seconds) to indicate that the cookie expires when the browser closes.
	Expiration string `json:"expiration,omitempty"`
}
