/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmAuthLdap struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Specifies the name of a SSL client certificate. The default value is none.
	SslClientCert string `json:"sslClientCert,omitempty"`

	// Specifies the LDAP servers that the system must use to obtain authentication information. You must specify a server when you create an LDAP configuration object.
	Servers string `json:"servers,omitempty"`

	// Specifies SSL ciphers.The default value is none.
	SslCiphers string `json:"sslCiphers,omitempty"`

	// Specifies the name of an SSL CA certificate. The default value is none.
	SslCaCertFile string `json:"sslCaCertFile,omitempty"`

	// Specifies the group distinguished name. The system uses this option for authorizing client traffic.
	GroupDn string `json:"groupDn,omitempty"`

	// Specifies the port name or number for the LDAP service. Port 389 is typically used for non-SSL and port 636 is used for an SSL-enabled LDAP service.
	Port int64 `json:"port,omitempty"`

	// Specifies a bind timeout limit, in seconds. The default value is 30 seconds.
	BindTimeout int64 `json:"bindTimeout,omitempty"`

	// Specifies the name of a SSL client key. The default value is none.
	SslClientKey string `json:"sslClientKey,omitempty"`

	// Specifies the version number of the LDAP application. The default value is 3.
	Version int64 `json:"version,omitempty"`

	// Specifies the password for the search account created on the LDAP server. This option is required if you use a bind DN.
	BindPw string `json:"bindPw,omitempty"`

	// Specifies the search base distinguished name. The default value is none.
	SearchBaseDn string `json:"searchBaseDn,omitempty"`

	// Specifies a logon attribute. Normally, the value of this option is uid; however, if the server is a Microsoft Windows Active Directory server, the value must be the account name samaccountname (not case-sensitive).
	LoginAttribute string `json:"loginAttribute,omitempty"`

	// Specifies the search timeout, in seconds. The default value is 30 seconds.
	SearchTimeout int64 `json:"searchTimeout,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Enables or disables warning messages. The default value is enabled.
	Warnings string `json:"warnings,omitempty"`

	// Specifies whether to verify a user's group membership given in the remote-role definitions, formatted as \"*member*of= group-dn \".
	CheckRolesGroup string `json:"checkRolesGroup,omitempty"`

	// Specifies that the system checks an SSL peer. The default value is disabled.
	SslCheckPeer string `json:"sslCheckPeer,omitempty"`

	// Specifies whether the system ignores an unknown user. The default value is disabled.
	IgnoreUnknownUser string `json:"ignoreUnknownUser,omitempty"`

	// Enables or disables SSL. The default value is disabled. Note that when you use the command line interface to enable SSL for an LDAP service, the system does not change the service port number from 389 to 636, as is required. To change the port number from the command line, use the service option for this component, for example, ldap [name] ssl enabled service 636.
	Ssl string `json:"ssl,omitempty"`

	// Specifies whether the system ignores authentication information if it is not available. The default value is disabled.
	IgnoreAuthInfoUnavail string `json:"ignoreAuthInfoUnavail,omitempty"`

	// Specifies the search scope. The default value is sub.
	Scope string `json:"scope,omitempty"`

	// Specifies a group member attribute. The system uses this option for authorizing client traffic.
	GroupMemberAttribute string `json:"groupMemberAttribute,omitempty"`

	// Specifies the distinguished name of an account to which to bind, in order to perform searches. This search account is a read-only account used to do searches. The admin account can be used as the search account. If no admin DN is specified, then no bind is attempted. This option is only required when a site does not allow anonymous searches. If the remote server is a Microsoft Windows Active Directory server, the distinguished name must be in the form of an email address.
	BindDn string `json:"bindDn,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Displays the partition within which the server resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the idle timeout, in seconds, for connections. The default value is 3600 seconds.
	IdleTimeout int64 `json:"idleTimeout,omitempty"`

	// Specifies a filter. Use this option for authorizing client traffic.
	Filter string `json:"filter,omitempty"`

	// Specifies a user template for the LDAP application to use for authentication. The default value is none.
	UserTemplate string `json:"userTemplate,omitempty"`

	// Enables or disables syslog-ng debugging information at LOG DEBUG level. The default value is disabled. F5 Networks does not recommend using this option for a normal configuration.
	Debug string `json:"debug,omitempty"`

	// Confirms the password for the bind distinguished name. This option is optional. The default value is disabled.
	CheckHostAttr string `json:"checkHostAttr,omitempty"`
}
