/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmPool struct {

	// Enables or disables the min-up-members feature. If you enable this feature, you must also specify a value for both the min-up-members and min-up-members-action options.
	MinUpMembersChecking string `json:"minUpMembersChecking,omitempty"`

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Specifies the Quality of Service (QoS) level to use when sending packets to a server. The default value is 65535 (pass-through).
	LinkQosToServer string `json:"linkQosToServer,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the maximum time, in milliseconds, a connection will remain enqueued. The default is zero which indicates there is no limit.
	QueueTimeLimit int64 `json:"queueTimeLimit,omitempty"`

	// Specifies the minimum number of members that must be up for traffic to be confined to a priority group when using priority-based activation. The default value is 0 (zero). An active member is a member that is up (not marked down) and is handling fewer connections than its connection limit.
	MinActiveMembers int64 `json:"minActiveMembers,omitempty"`

	// Specifies the Type of Service (ToS) level to use when sending packets to a server. 65534 (mimic) specifies that the system sets the ToS level of outgoing packets to the same ToS level of the most-recently received incoming packet. The default value is 65535 (pass-through).
	IpTosToServer string `json:"ipTosToServer,omitempty"`

	// Specifies the modes that the system uses to load balance name resolution requests among the members of this pool. See \"help pool\" for a description of each loading balancing mode.
	LoadBalancingMode string `json:"loadBalancingMode,omitempty"`

	// Specifies that the pool is a gateway failsafe pool in a redundant configuration. This string identifies the device that will failover when the monitor reports the pool member down. By default the device string is empty.
	GatewayFailsafeDevice string `json:"gatewayFailsafeDevice,omitempty"`

	// Specifies whether the pool can load balance NAT connections. The default value is yes.
	AllowNat string `json:"allowNat,omitempty"`

	// autoscale-group id to which pool members belong to.
	AutoscaleGroupId string `json:"autoscaleGroupId,omitempty"`

	// Specifies the maximum number of connections that may simultaneously be queued to go to any member of this pool. The default is zero which indicates there is no limit.
	QueueDepthLimit int64 `json:"queueDepthLimit,omitempty"`

	// Enable or disable queuing connections when pool member or node connection limits are reached. When queuing is not enabled, new connections are reset when connection limits are met.
	QueueOnConnectionLimit string `json:"queueOnConnectionLimit,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the minimum number of pool members that must be up; otherwise, the system takes the action specified in the min-up-members-action option. Use this option for gateway pools in a redundant system where a unit number is applied to a pool. This indicates that the pool is only configured on the specified unit.
	MinUpMembers int64 `json:"minUpMembers,omitempty"`

	// Specifies the Type of Service (ToS) level to use when sending packets to a client. 65534 (mimic) specifies that the system sets the ToS level of outgoing packets to the same ToS level of the most-recently received incoming packet. The default value is 65535 (pass-through).
	IpTosToClient string `json:"ipTosToClient,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the health monitors that the system uses to determine whether it can use this pool for load balancing. The monitor marks the pool up or down based on whether the monitor(s) are successful. You can specify a single monitor, multiple monitors \"http and https\", or a \"min\" rule, \"min 1 of { http https }\". You may remove the monitor by specifying \"none\".
	Monitor string `json:"monitor,omitempty"`

	// Displays the administrative partition within which the pool resides.
	Partition string `json:"partition,omitempty"`

	// Specifies, in seconds, the ramp time for the pool. This provides the ability to cause a pool member that has just been enabled, or marked up, to receive proportionally less traffic than other members in the pool. The proportion of traffic the member accepts is determined by how long the member has been up in comparison to the slow-ramp-time setting for the pool.For example, if the load-balancing-mode of a pool is round-robin, and it has a slow-ramp-time of 60 seconds, when a pool member has been up for only 30 seconds, the pool member receives approximately half the amount of new traffic as other pool members that have been up for more than 60 seconds. After the pool member has been up for 45 seconds, it receives approximately three quarters of the new traffic.The slow ramp time is particularly useful when used with the least-connections-member load balancing mode. The default value is 10.
	SlowRampTime int64 `json:"slowRampTime,omitempty"`

	// Specifies whether the pool can load balance SNAT connections. The default value is yes.
	AllowSnat string `json:"allowSnat,omitempty"`

	// Specifies the action to take if the min-up-members-checking is enabled and the number of active pool members falls below the number specified in min-up-members. The default value is failover.
	MinUpMembersAction string `json:"minUpMembersAction,omitempty"`

	// Specifies the number of times the system tries to contact a pool member after a passive failure. A passive failure consists of a server-connect failure or a failure to receive a data response within a user-specified interval. The default is 0 (zero), which indicates no reselect attempts.
	ReselectTries int64 `json:"reselectTries,omitempty"`

	// Specifies the action to take if the service specified in the pool is marked down. The default value is none.
	ServiceDownAction string `json:"serviceDownAction,omitempty"`

	// Do not count the weight of persisted connections on pool members when making load balancing decisions.
	IgnorePersistedWeight string `json:"ignorePersistedWeight,omitempty"`

	// Specifies the Quality of Service (QoS) level to use when sending packets to a client. The default value is 65535 (pass-through).
	LinkQosToClient string `json:"linkQosToClient,omitempty"`
}
