/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmMessageRoutingGenericRouter struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// The maximum number of bytes worth of pending messages that will be held while waiting for a connection to a peer to be created. Once reached, any additional messages to the peer will be flagged as undeliverable and returned to the originator.
	MaxPendingBytes int64 `json:"maxPendingBytes,omitempty"`

	// The maximum number of pending messages that will be held while waiting for a connection to a peer to be created. Once reached, any additional messages to the peer will be flagged as undeliverable and returned to the originator.
	MaxPendingMessages int64 `json:"maxPendingMessages,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Specifies the traffic group of the router. The default is inherited from the containing folder.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// If true, the router will route a message to an existing connection on the same TMM as the message was received on. If an existing connection is not found, it will route the message through an existing connection based on a deterministic algorithm that may be on another TMM. If a matching existing connection is not found, it will create a connection on the current TMM. Setting this flag may limit the number of connections that are created to a peer.
	UseLocalConnection string `json:"useLocalConnection,omitempty"`

	// If set, the remote port on clientside connections (connections where the peer connected to the BIG IP) is ignored when searching for an existing connection.
	IgnoreClientPort string `json:"ignoreClientPort,omitempty"`

	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all of the settings and values from the specified parent profile.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
