/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmDnsCacheTransparent struct {
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Idx float32 `json:"idx,omitempty"`

	// Number of bytes allocated for the message cache. The default value is 1m
	MsgCacheSize int64 `json:"msgCacheSize,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Answer queries for default zones: localhost, reverse 127.0.0.1 and ::1, and AS112 zones. The default value is no.
	AnswerDefaultZones string `json:"answerDefaultZones,omitempty"`

	// Zones and associated resource records for which the cache will provide Authoritative answers.
	LocalZones string `json:"localZones,omitempty"`

	// Number of bytes allocated for the resource record set cache. The default value is 10m.
	RrsetCacheSize int64 `json:"rrsetCacheSize,omitempty"`

	Type_ string `json:"type,omitempty"`
}
