/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileDns struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Set DNS64 additional section rewriting
	Dns64AdditionalSectionRewrite string `json:"dns64AdditionalSectionRewrite,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Set DNS64 mapping mode
	Dns64 string `json:"dns64,omitempty"`

	// Indicates whether the dns-express service is enabled. The service handles zone transfers from the primary DNS server.
	EnableDnsExpress string `json:"enableDnsExpress,omitempty"`

	// When Rapid Response is enabled, what to do with non-matching DNS queries.
	RapidResponseLastAction string `json:"rapidResponseLastAction,omitempty"`

	// Indicates whether to perform DNS packet logging.
	EnableLogging string `json:"enableLogging,omitempty"`

	// IPv6 prefix for DNS64 mapping
	Dns64Prefix string `json:"dns64Prefix,omitempty"`

	// Indicates whether the system answers zone transfer requests for a DNS zone created on the system.
	ProcessXfr string `json:"processXfr,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Indicates whether DNS firewall capability is enabled.
	EnableDnsFirewall string `json:"enableDnsFirewall,omitempty"`

	// Sets AVR DNS statistics sampling rate. 0: no query will be sent to the analytics database. 1: every query will be sent. N: every Nth query will be sent and the analytics database will count it N times. The default value is 0. When sampling rate is greater than one, the statistics will be inaccurate if the traffic volume is low. However, when the traffic volume is high, the system performance will benefit from sampling and the inaccuracy will be negligible. The sampling rate does not apply to DNS firewall statistics.
	AvrDnsstatSampleRate int64 `json:"avrDnsstatSampleRate,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Indicates whether to allow the BIG-IP global traffic management system to handle DNS resolution for DNS queries and responses that contain wide IP names. The default value is yes.
	EnableGtm string `json:"enableGtm,omitempty"`

	// Indicates whether to process clientside DNS packets with Recursion Desired set in the header.
	ProcessRd string `json:"processRd,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// On supported platforms, indicates whether the hardware will accelerate query validation.
	EnableHardwareQueryValidation string `json:"enableHardwareQueryValidation,omitempty"`

	// Last action to take if query name doesn't match.
	UnhandledQueryAction string `json:"unhandledQueryAction,omitempty"`

	// Forward non-GTM and non-dns-express requests to local BIND.
	UseLocalBind string `json:"useLocalBind,omitempty"`

	// Indicates the DNS security profile the system uses.
	DnsSecurity string `json:"dnsSecurity,omitempty"`

	// On supported platforms, indicates whether the hardware will cache responses.
	EnableHardwareResponseCache string `json:"enableHardwareResponseCache,omitempty"`

	// Indicates whether to allow queries to be answered non-authoritatively by a DNS cache.
	EnableCache string `json:"enableCache,omitempty"`

	// DNS cache used to generate non-authoritative responses.
	Cache string `json:"cache,omitempty"`

	// Indicates whether to perform DNS Security Extensions.
	EnableDnssec string `json:"enableDnssec,omitempty"`

	// Indicates whether to allow queries to be answered by Rapid Response DNS.
	EnableRapidResponse string `json:"enableRapidResponse,omitempty"`

	// Selects the desired logging profile.
	LogProfile string `json:"logProfile,omitempty"`
}
