/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmDnsDnssecKeyTmGeneration struct {
	AppService string `json:"appService,omitempty"`

	// DNSSEC key tag generated from rdata of DNSKEY
	KeyTag int64 `json:"keyTag,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// handle used for interaction with key manager or HSM.
	Handle string `json:"handle,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Hostname of BIG-IP which created this DNSSEC key generation.
	Creator string `json:"creator,omitempty"`

	// Public key.
	PublicText string `json:"publicText,omitempty"`

	// Specifies the date and time that the key expires.
	Expiration string `json:"expiration,omitempty"`

	// Specifies the date and time that the key rolls over to a new key.
	Rollover string `json:"rollover,omitempty"`

	PrivateText string `json:"privateText,omitempty"`
}
