/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmNodeFqdn struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the number of attempts to resolve a domain name. The default is 5.
	DownInterval int64 `json:"downInterval,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the amount of time before sending the next DNS query.
	Interval string `json:"interval,omitempty"`

	// Specifies the node's address family. The default is 'unspecified', or IP-agnostic
	AddressFamily string `json:"addressFamily,omitempty"`

	// Specifies the fully qualified domain name of the node.
	TmName string `json:"tmName,omitempty"`

	// Specifies whether the node should scale to the IP address set returned by DNS.
	Autopopulate string `json:"autopopulate,omitempty"`
}
