/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type LtmProfileRadius struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// The list of host and network addresses from which clients can connect. Any entry in the list can be a host or network address: 10.10.10.0/24 or 10.10.10.10. A value of \"none\" indicates that any client can connect. The default value is \"none\".
	Clients string `json:"clients,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// Specifies PEM protocol profile to be used when subscriber discovery is enabled. PEM protocol profile defines mapping of RADIUS AVPs to subscriber ID and other PEM subscriber session attributes.
	PemProtocolProfileRadius string `json:"pemProtocolProfileRadius,omitempty"`

	// Specifies the name of the RADIUS attribute used to persist on. It can be an ASCII string or numeric code (1-255). Acceptable strings are from RFC 2865 section 5. A value of \"none\" indicates that persistence is disabled. The default value is \"none\".
	PersistAvp string `json:"persistAvp,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified. The default value is radius.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Enables PEM subscriber discovery based on the content of RADIUS packets.
	SubscriberDiscovery string `json:"subscriberDiscovery,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
