/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type MessageRoutingSipProfileSession struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Indicates the maximum number acceptable SIP message size (in bytes).
	MaxMsgSize int64 `json:"maxMsgSize,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Indicates the maximum count of expected SIP message header fields.
	MaxMsgHeaderCount int64 `json:"maxMsgHeaderCount,omitempty"`

	// Enables or disables the insertion of a record-route header in requests that establish dialog.
	InsertRecordRouteHeader string `json:"insertRecordRouteHeader,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Enables or disables loop-detection checking
	LoopDetection string `json:"loopDetection,omitempty"`

	// Enables or disables honoring any via which is not inserted by the system for routing the response.
	HonorVia string `json:"honorVia,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all of the settings and values from the specified parent profile.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the custom value for the sent-by field of via
	CustomVia string `json:"customVia,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Enables or disables checking on max-forwards.
	MaxForwardsCheck string `json:"maxForwardsCheck,omitempty"`

	// Indicates whether SIP firewall capability is enabled.
	EnableSipFirewall string `json:"enableSipFirewall,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Enables or disables whether a connection to a request originator is re-established (if it no longer exists) in order to deliver a response.
	DoNotConnectBack string `json:"doNotConnectBack,omitempty"`

	// Indicates the maximum SIP message header size (in bytes).
	MaxMsgHeaderSize int64 `json:"maxMsgHeaderSize,omitempty"`

	// Enables or disables sending failure response messages such as 4xx, 5xx and 6xx, when a SIP request is being dropped.
	GenerateResponseOnFailure string `json:"generateResponseOnFailure,omitempty"`

	// Enables or disables insertion of top via.
	InsertViaHeader string `json:"insertViaHeader,omitempty"`
}
