/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type MonitorSasp struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	Destination string `json:"destination,omitempty"`

	// Specifies the protocol that the monitor uses to communicate with the target. The options are tcp and udp. The default value is tcp.
	Protocol string `json:"protocol,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	MonInterval int64 `json:"monInterval,omitempty"`

	// Specifies the existing monitor from which the system imports settings for the new monitor.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the port through which the SASP monitor communicates with the Group Workload Manager. The default port is 3000.
	Service string `json:"service,omitempty"`

	// Specifies the frequency at which the system queries the Group Workload Manager (GWM). The default value is auto. You can specify a range between 10 and 600 seconds.
	Interval string `json:"interval,omitempty"`

	// Specifies the IP address of the Primary Group Workload Manager.
	PrimaryAddress string `json:"primaryAddress,omitempty"`

	// Specifies the IP address of the Secondary Group Workload Manager.
	SecondaryAddress string `json:"secondaryAddress,omitempty"`

	// Displays the administrative partition within which the monitor resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the amount of time in seconds after the first successful response before a node will be marked up.  A value of 0 will cause a node to be marked up immediately after a valid  response is received from the node. The default setting is 0.
	TimeUntilUp int64 `json:"timeUntilUp,omitempty"`

	// Specifies whether the load balancer should send Get Weight Request messages (pull) or receive Send Weight messages (push) from the GWM. The default mode is pull.
	Mode string `json:"mode,omitempty"`

	// Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 100 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
	Timeout int64 `json:"timeout,omitempty"`
}
