/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type MonitorModuleScore struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	Destination string `json:"destination,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies how often in seconds that the system issues the monitor check when the node is up. The default value is the same as the (down) interval.
	UpInterval int64 `json:"upInterval,omitempty"`

	// Specifies the IP address of the SNMP server. The default value is none.
	SnmpIpAddress string `json:"snmpIpAddress,omitempty"`

	// Specifies the name of the monitor from which you want the custom monitor to inherit settings. The default value is module_score.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the SNMP version in use by the system. The default value is v2c.
	SnmpVersion string `json:"snmpVersion,omitempty"`

	// Specifies the port associated with the SNMP server. The default value is 161.
	SnmpPort int64 `json:"snmpPort,omitempty"`

	// Specifies a Local Traffic Manager pool name. Use this option if you want the system to set dynamic ratios on a pool member instead of on the associated node for the pool member. The default value is none.
	Pool string `json:"pool,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the frequency at which the system issues the monitor check. The default value is 10 seconds.
	Interval int64 `json:"interval,omitempty"`

	// Displays the administrative partition within which the monitor resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the amount of time in seconds after the first successful response before a node will be marked up.  A value of 0 will cause a node to be marked up immediately after a valid  response is received from the node. The default setting is 0.
	TimeUntilUp int64 `json:"timeUntilUp,omitempty"`

	// Specifies the identifier for the SNMP community. The default value is public.
	SnmpCommunity string `json:"snmpCommunity,omitempty"`

	// Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 30 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
	Timeout int64 `json:"timeout,omitempty"`

	// Specifies whether the monitor sends error messages and additional information to a log file created and labeled specifically for this monitor. You can use the log information to help diagnose and troubleshoot unsuccessful health checks. The default value is no.
	Debug string `json:"debug,omitempty"`
}
