/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type MonitorDiameter struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// The IANA SMI Network Management Private Enterprise Codes value assigned to the vendor of the Diameter application.
	VendorId string `json:"vendorId,omitempty"`

	Destination string `json:"destination,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// The Host-IP-Address is used to inform a Diameter peer of the sender's IP address.
	HostIpAddress string `json:"hostIpAddress,omitempty"`

	// Specifies how often in seconds that the system issues the monitor check when the node is up. The default value is the same as the (down) interval.
	UpInterval int64 `json:"upInterval,omitempty"`

	// Used to advertise support of a vendor-specific Diameter Application.  Exactly one of the Auth-Application-Id and Acct-Application-Id AVPs MAY be present.
	VendorSpecificAcctApplicationId string `json:"vendorSpecificAcctApplicationId,omitempty"`

	// Used to advertise support of the Authentication and Authorization portion of an application.  Exactly one of the Auth-Application-Id and Acct-Application-Id AVPs MAY be present.
	AuthApplicationId string `json:"authApplicationId,omitempty"`

	// Identifies the endpoint that originated the Diameter message.
	OriginHost string `json:"originHost,omitempty"`

	// Specifies whether the system automatically changes the status of a resource to up at the next successful monitor check. The default value of the manual-resume option is disabled. Note that if you set the manual-resume option to enabled, you must manually mark the resource as up before the system can use it for load balancing connections.
	ManualResume string `json:"manualResume,omitempty"`

	// Used to advertise support of a vendor-specific Diameter Application.  Exactly one of the Auth-Application-Id and Acct-Application-Id AVPs MAY be present.
	VendorSpecificAuthApplicationId string `json:"vendorSpecificAuthApplicationId,omitempty"`

	// Specifies the frequency at which the system issues the monitor check. The default value is 10 seconds.
	Interval int64 `json:"interval,omitempty"`

	// Specifies the existing monitor from which the system imports settings for the new monitor.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// The vendor assigned name for the product.  The Product-Name SHOULD remain constant across firmware revisions for the same product.
	ProductName string `json:"productName,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Displays the administrative partition within which the monitor resides.
	Partition string `json:"partition,omitempty"`

	// The vendor id for a vendor-specific Diameter Application.
	VendorSpecificVendorId string `json:"vendorSpecificVendorId,omitempty"`

	// Specifies the amount of time in seconds after the first successful response before a node will be marked up.  A value of 0 will cause a node to be marked up immediately after a valid  response is received from the node. The default setting is 0.
	TimeUntilUp int64 `json:"timeUntilUp,omitempty"`

	// The Realm of the originator of any Diameter message
	OriginRealm string `json:"originRealm,omitempty"`

	// Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 31 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
	Timeout int64 `json:"timeout,omitempty"`

	// Used to advertise support of the Accounting portion of an application. Exactly one of the Auth-Application-Id and Acct-Application-Id AVPs MAY be present.
	AcctApplicationId string `json:"acctApplicationId,omitempty"`
}
