/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type MonitorSip struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Specifies the IP address and service port of the resource that is the destination of this monitor. Possible values are:  *:* (Specifies to perform a health check on the IP address and port supplied by a pool member), *:port (Specifies to perform a health check on the server with the IP address supplied by the pool member and the port you specify.), and  IP : port  (Specifies to mark a pool member up or down based on the response of the server at the IP address and port you specify.).
	Destination string `json:"destination,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies how often in seconds that the system issues the monitor check when the node is up. The default value is the same as the (down) interval.
	UpInterval int64 `json:"upInterval,omitempty"`

	// Specifies the SIP status codes that the target can return to be considered down. By default the system always accepts status codes according to sip-monitor.filter. After checking that, the status code is checked against this key. The options are none (Specifies that the monitor does not specifically reject any other SIP status codes.), any (Specifies that the monitor rejects all SIP status codes that are not in the sip-monitor.filter property.), and status (Specifies one or more status codes that you want to add to the monitor.)  If a code is also in sip-monitor.filter, the node will be marked up.
	FilterNeg string `json:"filterNeg,omitempty"`

	// Specifies whether the system automatically changes the status of a resource to enabled at the next successful monitor check. If you set this option to yes, you must manually re-enable the resource before the system can use it for load balancing connections.
	ManualResume string `json:"manualResume,omitempty"`

	// Specifies the key if the monitored target requires authentication.
	Key string `json:"key,omitempty"`

	// Specifies the frequency at which the system issues the monitor check. The default value is 5 seconds.
	Interval int64 `json:"interval,omitempty"`

	// Specifies the existing monitor from which the system imports settings for the new monitor.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies, when enabled, that the SSL options setting (in OpenSSL) is set to ALL.
	Compatibility string `json:"compatibility,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the set of SIP headers in the SIP message that is sent to the target. Each header should be separated by a newline.
	Headers string `json:"headers,omitempty"`

	// Displays the administrative partition within which the monitor resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the SIP request line in the SIP message that is sent to the target.
	Request string `json:"request,omitempty"`

	// Specifies the SIP status codes that the target can return to be considered up. By default the system always accepts status codes whose value is in the 100, 200 or 300s. The options are none (Specifies that the monitor does not accept any other SIP status codes.), any (Specifies that the monitor accepts any SIP status codes.), and status (Specifies one or more status codes that you want to add to the monitor.)
	Filter string `json:"filter,omitempty"`

	// Specifies the amount of time in seconds after the first successful response before a node will be marked up.  A value of 0 will cause a node to be marked up immediately after a valid  response is received from the node. The default setting is 0.
	TimeUntilUp int64 `json:"timeUntilUp,omitempty"`

	// Specifies a fully-qualified path for a client certificate that the monitor sends to the target SSL server.
	Cert string `json:"cert,omitempty"`

	// Specifies the protocol that the monitor uses to communicate with the target. The options are tcp (the monitor uses TCP to communicate with the target) tls (the monitor uses TLS to communicate with the target) sips (the monitor uses TLS to communicate with the target, and the SIP URI is SIPS) and udp (the monitor uses UDP to communicate with the target)
	Mode string `json:"mode,omitempty"`

	// Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 16 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
	Timeout int64 `json:"timeout,omitempty"`

	// Specifies the list of ciphers for this monitor. The default value is \"DEFAULT:+SHA:+3DES:+kEDH\".
	Cipherlist string `json:"cipherlist,omitempty"`

	// Specifies whether the monitor sends error messages and additional information to a log file created and labeled specifically for this monitor. The default setting is no. You can use the log information to help diagnose and troubleshoot unsuccessful health checks. The options are: no (Specifies that the system does not redirect error messages and additional information related to this monitor.) and yes (Specifies that the system redirects error messages and additional information to the /var/log/monitors/ monitor_name - node_name - port .log file.).
	Debug string `json:"debug,omitempty"`
}
