/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetTunnelsTunnel struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Specifies the profile that you want to associate with the tunnel. The default value is gre.
	Profile string `json:"profile,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Enables or disables the tunnel to use the PMTU (Path MTU) information provided by ICMP NeedFrag error messages. If enabled and the tunnel MTU is set to 0, the tunnel will use the PMTU information. If enabled and the tunnel MTU is fixed to a non-zero value, the tunnel will use the minimum of PMTU and MTU. If disabled, the tunnel will use fixed MTU or calculate its MTU using tunnel encapsulation configurations.
	UsePmtu string `json:"usePmtu,omitempty"`

	// Specifies a traffic-group for use with the tunnel. Traffic group determines the ConfigSync behavior of the tunnel object.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// The key field may represent different values depending on the type of the tunnel. E.g. it represents the Virtual Network Identifier(VNI) for VXLAN tunnels. The default value is 0.
	Key int64 `json:"key,omitempty"`

	// Displays the index assigned to this tunnel. It is a unique identifier assigned for all objects displayed in the SNMP IF-MIB.
	IfIndex int64 `json:"ifIndex,omitempty"`

	// Specifies the maximum transmission unit (MTU) of the tunnel. The default value is the MTU of the tunnel's underlying interface minus the the encapsulation overhead introduced by the tunneling protocol in use for the tunnel.
	Mtu int64 `json:"mtu,omitempty"`

	// Enables or disables the tunnel to be transparent. If enabled, the user can inspect and/or manipulate the encapsulated traffic flowing through the BIG-IP. A transparent tunnel terminates a tunnel while presenting the illusion that the tunnel transits the device unperturbed i.e. the BIG-IP appears like an intermediate router that simply routes IP traffic through the device. The default value is disabled.
	Transparent string `json:"transparent,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies a remote IP address. This option is required.
	RemoteAddress string `json:"remoteAddress,omitempty"`

	// Specifies a value for insertion into the Type of Service (ToS) octet within the IP header of the encapsulating header of transmitted packets. The default value is preserve, which will cause the ToS octet from the encapsulated packet header to be copied into the ToS octet of the encapsulating packet header. The valid range is zero to 255
	Tos string `json:"tos,omitempty"`

	// Displays the admin-partition within which this component resides.
	Partition string `json:"partition,omitempty"`

	// Specifies an idle timeout for wildcard tunnels in seconds. This setting specifies the number of seconds that a wildcard tunnel connection is idle before the connection is eligible for deletion. The default value is 300 seconds.
	IdleTimeout int64 `json:"idleTimeout,omitempty"`

	// Specifies a secondary non-floating IP address when the local-address is set to a floating address. Currently this setting is supported by NVGRE tunnels only.
	SecondaryAddress string `json:"secondaryAddress,omitempty"`

	// Specifies a local IP address. This option is required.
	LocalAddress string `json:"localAddress,omitempty"`

	// Specifies how the tunnel carries traffic. The default value is bidirectional.
	Mode string `json:"mode,omitempty"`

	// Specifies whether auto lasthop is enabled or not. The default is to use next levels default.
	AutoLasthop string `json:"autoLasthop,omitempty"`
}
