/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetTmInterface struct {

	// Specifies the settings for a fixed (non-pluggable) interface. Use this option only with a combo port to specify the media type for the fixed interface, when it is not the preferred port.
	MediaFixed string `json:"mediaFixed,omitempty"`

	// Displays the MAC address (6-byte Ethernet address in hexadecimal colon notation, for example, 00:0b:09:88:00:9a) of the interface. This is the hardware address.
	MacAddress string `json:"macAddress,omitempty"`

	LldpTlvmap int64 `json:"lldpTlvmap,omitempty"`

	// Displays the name of the vendor of the pluggable unit on an interface.
	Vendor string `json:"vendor,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Sets STP automatic edge port detection for the interface. The default value is true. When automatic edge port detection is set to true for an interface, the system monitors the interface for incoming STP, RSTP, or MSTP packets. If no such packets are received for a sufficient period of time (about three seconds), the interface is automatically given edge port status. When automatic edge port detection is set to false for an interface, the system never gives the interface edge port status automatically. Any STP setting set on a per-interface basis applies to all spanning tree instances.
	StpAutoEdgePort string `json:"stpAutoEdgePort,omitempty"`

	// Resets STP, which forces a migration check.
	StpReset bool `json:"stpReset,omitempty"`

	// Indicates which side of a combo port the interface uses, if both sides have the potential for an external link. The default value for a combo port is sfp. Do not use this option for non-combo ports.
	PreferPort string `json:"preferPort,omitempty"`

	// Enables or disables STP. If you disable STP, no STP, RSTP, or MSTP packets are transmitted or received on the interface or trunk, and spanning tree has no control over forwarding or learning on the port or the trunk. The default value is enabled.
	Stp string `json:"stp,omitempty"`

	Bundle string `json:"bundle,omitempty"`

	// Disables the specified interfaces from passing traffic.
	Disabled bool `json:"disabled,omitempty"`

	// Specifies the settings for an SFP (pluggable) interface. Use this option only with a combo port to specify the media type for the SFP interface, when it is not the preferred port.
	MediaSfp string `json:"mediaSfp,omitempty"`

	// Specifies whether the interface connects to an end station instead of another spanning tree bridge. The default value is true.
	StpEdgePort string `json:"stpEdgePort,omitempty"`

	// Displays the index assigned to this interface. It is a unique identifier assigned for all objects displayed in the SNMP IF-MIB.
	IfIndex int64 `json:"ifIndex,omitempty"`

	// Displays the serial number of the pluggable unit on an interface.
	Serial string `json:"serial,omitempty"`

	// Displays the maximum media value for the interface.
	MediaMax string `json:"mediaMax,omitempty"`

	// Specifies the STP link type for the interface. The default value is auto. The spanning tree system includes important optimizations that can only be used on point-to-point links, that is, on links which connect just two bridges. If these optimizations are used on shared links, incorrect or unstable behavior may result. By default, the implementation assumes that full-duplex links are point-to-point and that half-duplex links are shared.
	StpLinkType string `json:"stpLinkType,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the protocol identifier associated with the tagged mode of the interface.
	QinqEthertype string `json:"qinqEthertype,omitempty"`

	// Specifies the settings for the interface. When you set the media option, the system automatically sets the media-sfp or media-fixed option based on whether the interface is a small form factor pluggable (SFP) interface, or for combo ports whether SFP is the preferred port.
	Media string `json:"media,omitempty"`

	// Enables the specified interfaces to pass traffic.
	Enabled bool `json:"enabled,omitempty"`

	// Displays the maximum Transmission Unit (MTU) of the interface, which is the maximum number of bytes in a frame without IP fragmentation.
	Mtu int64 `json:"mtu,omitempty"`

	LldpAdmin string `json:"lldpAdmin,omitempty"`

	// Specifies how the system controls the sending of PAUSE frames. The default value is tx-rx.
	FlowControl string `json:"flowControl,omitempty"`

	// Enables or disables forcing of gigabit fiber media. If this is enabled for a gigabit fiber interface, the media setting will be forced, and no auto-negotiation will be performed. If it is disabled, auto-negotiation will be performed with just a single gigabit fiber option advertised.
	ForceGigabitFiber string `json:"forceGigabitFiber,omitempty"`

	// Displays the current media settings for the interface.
	MediaActive string `json:"mediaActive,omitempty"`
}
