/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetStpInterfaces struct {
	AppService string `json:"appService,omitempty"`

	// Specifies the interface priority number. Each network interface has an associated priority within each spanning tree instance. The relative values of the interface priorities influence which interfaces are chosen to carry network traffic. All other things being equal, interfaces with numerically lower priority values are favored to carry traffic. Interface priorities take values in the range 0-240 in steps of 16. The default interface priority is 128, the middle of the valid range.
	Priority int64 `json:"priority,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// The relative cost of send network traffic through the interface. The external path cost only applies to STP 0. See the help page for a detailed description.
	ExternalPathCost int64 `json:"externalPathCost,omitempty"`

	// The relative cost of send network traffic through the interface. See the help page for a detailed description.
	InternalPathCost int64 `json:"internalPathCost,omitempty"`

	Type_ string `json:"type,omitempty"`
}
