/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetIpsecIkeDaemon struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the logging level of the IKE daemon. The log file is located at /var/log/racoon.log.
	LogLevel string `json:"logLevel,omitempty"`

	// Specifies the logging publisher. A new log-publisher object can be created via TMSH command tmsh create sys log-config publisher.
	LogPublisher string `json:"logPublisher,omitempty"`

	// Specifies the port for the IKE daemon to accept ISAKMP messages. Only 500 is currently supported.
	IsakmpPort int64 `json:"isakmpPort,omitempty"`

	// Specifies the port for the IKE daemon to accept ISAKMP messages when NAT-Traversal is detected. This is also the port number to accept UDP-encapsulated ESP traffic for NAT-Traversal. Only 4500 is currently supported.
	IsakmpNattPort int64 `json:"isakmpNattPort,omitempty"`

	// Specifies the interval between sending NAT-Traversal keep-alive packets. The default value is 20 seconds. Set to 0 to disable keep-alive packets.
	NattKeepAlive int64 `json:"nattKeepAlive,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
