/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetRateShapingQueue struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the interval in seconds at which the system reconfigures the SFQ hash function. This option applies only to the sfq type.
	SfqPerturbation int64 `json:"sfqPerturbation,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the bucket size in kilobytes or megabytes for the sfq type. The default value is 0 (zero).
	SfqBucketSize int64 `json:"sfqBucketSize,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the size in kilobytes or megabytes of the largest queue for the pfifo type only. The default value is 0 (zero).
	PfifoMaxSize int64 `json:"pfifoMaxSize,omitempty"`

	// Specifies the queue discipline this custom queue uses. The available values are none, sfq, and pfifo. See the help page for a more detailed description.
	Type_ string `json:"type,omitempty"`

	// Specifies the size in kilobytes or megabytes of the smallest queue for the pfifo type only. The default value is 0 (zero).
	PfifoMinSize int64 `json:"pfifoMinSize,omitempty"`

	// Specifies the number of buckets in kilobytes or megabytes into which the queue is divided when you are configuring the sfq type. Valid values are 0, 16, 32, 64, 128, 256, 512, and 1024. The default value is 0 (zero).
	SfqBucketCount int64 `json:"sfqBucketCount,omitempty"`
}
