/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetTunnelsPpp struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Number of consecutive PPP LCP echo messages that must go unanswered for the server to drop PPP connection. For example, if the server sends  number  of consecutive PPP LCP Echo Request messages that go unanswered (by Echo Reply), it will close the PPP connection.
	LcpEchoFailure int64 `json:"lcpEchoFailure,omitempty"`

	// Displays the admin-partition within which this component resides.
	Partition string `json:"partition,omitempty"`

	Ipcp string `json:"ipcp,omitempty"`

	// The profile from which to inherit settings. The default value is ppp.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	Ipv6cp string `json:"ipv6cp,omitempty"`

	// VJ is a data compression protocol described in RFC 1144, specifically designed by Van Jacobson to improve TCP/IP performance over slow serial links. Van Jacobson Header Compression (also known as VJ compression, or just Header Compression) is an option in most versions of PPP.
	Vj string `json:"vj,omitempty"`

	// Specifies interval in seconds between PPP LCP Echo Request messages that the server sends to the peer (client).
	LcpEchoInterval int64 `json:"lcpEchoInterval,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
