/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetRateShapingShapingPolicy struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the percentage of the maximum throughput rate specified for the parent in the rate class command that is available for this traffic flow.
	RatePercentage float32 `json:"ratePercentage,omitempty"`

	// Specifies the percentage of the ceiling rate specified for the parent in the rate class command that is available for this traffic flow.
	CeilingPercentage float32 `json:"ceilingPercentage,omitempty"`

	// Specifies the queue discipline for this traffic flow. The available pre-configured settings are pfifo (Priority First in, First out), sfq (Stochastic Fair Queuing), and none. The default value is none. You can create a customized queue discipline using the queue command.
	Queue string `json:"queue,omitempty"`

	// Specifies the drop policy for this traffic flow. The available pre-configured settings are tail (drops the end of the traffic stream), red (randomly drops packets), and fred (drops packets according to the type of traffic in the flow). The default value is none. You can create a customized drop policy using the drop-policy command.
	DropPolicy string `json:"dropPolicy,omitempty"`

	// Specifies the maximum number of bytes that traffic is allowed to burst beyond the base rate.
	MaxBurst int64 `json:"maxBurst,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
