/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetTunnels struct {

	// MAP tunnel profile configuration
	Map_ string `json:"map,omitempty"`

	// Geneve tunnel profile configuration
	Geneve string `json:"geneve,omitempty"`

	// 6RD tunnel profile configuration
	V6rd string `json:"v6rd,omitempty"`

	// PPP tunnel profile configuration
	Ppp string `json:"ppp,omitempty"`

	// EtherIP tunnel profile configuration
	Etherip string `json:"etherip,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// FEC tunnel profile configuration
	Fec string `json:"fec,omitempty"`

	// WCCP tunnel profile configuration
	Wccp string `json:"wccp,omitempty"`

	// Tunnel configuration
	Tunnel string `json:"tunnel,omitempty"`

	// IPIP tunnel profile configuration
	Ipip string `json:"ipip,omitempty"`

	// GRE tunnel profile configuration
	Gre string `json:"gre,omitempty"`

	TcpForward string `json:"tcpForward,omitempty"`

	// IPSEC tunnel profile configuration
	Ipsec string `json:"ipsec,omitempty"`

	// FEC tunnel statistic
	FecStat string `json:"fecStat,omitempty"`

	// VXLAN tunnel profile configuration
	Vxlan string `json:"vxlan,omitempty"`
}
