/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetIpsecTrafficSelector struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Specifies the destination IP address of the traffic to be matched.
	DestinationAddress string `json:"destinationAddress,omitempty"`

	// Specifies the name of the IPsec policy to be enforced on the matched traffic.
	IpsecPolicy string `json:"ipsecPolicy,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Specifies the direction of traffic to be protected with IPsec. If the direction is both, use source-address and destination-address with respect to the outbound direction. The default value is both.
	Direction string `json:"direction,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies how the system handles traffic that matches the criteria in the traffic selector. Only protect is currently supported.
	Action string `json:"action,omitempty"`

	// Specifies the destination port for which you want the traffic to be matched.
	DestinationPort int64 `json:"destinationPort,omitempty"`

	// Specifies the source port for which you want the traffic to be matched.
	SourcePort int64 `json:"sourcePort,omitempty"`

	// Specifies the IP protocol for which you want the traffic to be matched.
	IpProtocol int64 `json:"ipProtocol,omitempty"`

	// Specifies the source IP address of the traffic to be matched.
	SourceAddress string `json:"sourceAddress,omitempty"`

	// Specifies the order in which traffic is matched, if traffic can be matched to multiple traffic selectors.
	Order int64 `json:"order,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
