/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetRouterAdvertisement struct {
	AppService string `json:"appService,omitempty"`

	// Indicates the Managed address configuration flag field in the router advertisement be set to 1.
	Managed bool `json:"managed,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Name of the VLAN used by this router advertisement.
	Vlan string `json:"vlan,omitempty"`

	// Specifies the value to be used for the Router Lifetime field in the Router Advertisement. The default value is equal to 3 * max-interval. Valid values are between 600 and 9000.
	RouterLifetime string `json:"routerLifetime,omitempty"`

	// Disables router advertisement for the VLAN. This is the default.
	Disabled bool `json:"disabled,omitempty"`

	// Specifies the value to be used for the Retransmit Timer field in the Router Advertisement. The default is 0.
	RetransmitTimer int64 `json:"retransmitTimer,omitempty"`

	// Indicates the Managed address configuration flag field in the router advertisement be set to 0. This is the default.
	Unmanaged bool `json:"unmanaged,omitempty"`

	// Set a specific maximum transmission unit (MTU) for the VLAN. The default value is 0.
	Mtu int64 `json:"mtu,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Indicates the Other Configuration flag field in the router advertisement be set to 1.
	OtherConfig bool `json:"otherConfig,omitempty"`

	// Specifies the minimum time allowed between sending unsolicited multicast Router Advertisements from the interface, in seconds. The default value is 200.
	MinInterval int64 `json:"minInterval,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Defines the hop limit sent in the router advertisement. The range is from 0 to 255. The default value is 0.
	CurrentHopLimit int64 `json:"currentHopLimit,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Enables router advertisement for the VLAN.
	Enabled bool `json:"enabled,omitempty"`

	// Specifies the value to be used for the Reachable Time field in the Router Advertisement. The default is 0.
	ReachableTime int64 `json:"reachableTime,omitempty"`

	// Specifies the maximum time allowed between sending unsolicited multicast Router Advertisements from the interface, in seconds. The default value is 600.
	MaxInterval int64 `json:"maxInterval,omitempty"`

	// Indicates the Other Configuration flag field in the router advertisement be set to 0. This is the default.
	NoOtherConfig bool `json:"noOtherConfig,omitempty"`
}
