/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetCosGlobalSettings struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the precedence between handling of DSCP and 802.1p.
	Precedence string `json:"precedence,omitempty"`

	// enable global hardware 8 COS queue setting.
	FeatureEnabled bool `json:"featureEnabled,omitempty"`

	// Enables adding and removal of mappings between 802.1p field values and traffic priorities.
	DefaultMap8021p string `json:"defaultMap_8021p,omitempty"`

	// Specifies the default traffic-priority which is applied to all traffic that does not match a specified DSCP/802.1p field value.
	DefaultTrafficPriority string `json:"defaultTrafficPriority,omitempty"`

	// Enables adding and removal of mappings between DSCP field values and traffic priorities.
	DefaultMapDscp string `json:"defaultMapDscp,omitempty"`

	// disable global hardware 8 COS queue setting.
	FeatureDisabled bool `json:"featureDisabled,omitempty"`
}
