/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetSelf struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Staged firewall policy.
	FwStagedPolicy string `json:"fwStagedPolicy,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// The source of Self-IP
	AddressSource string `json:"addressSource,omitempty"`

	// Displays the admin-partition within which this self IP resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the traffic group.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// The traffic-group unit id in a redundant system.
	Unit int64 `json:"unit,omitempty"`

	// Enforced firewall policy.
	FwEnforcedPolicy string `json:"fwEnforcedPolicy,omitempty"`

	// The Self IP's address and netmask.
	Address string `json:"address,omitempty"`

	// The traffic-group specified floating IP address for a VLAN shared by all devices of the traffic-group.
	Floating string `json:"floating,omitempty"`

	// Indicates if the traffic-group for the Self IP is inherited from the parent folder.
	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`

	// Specifies the service policy to use.
	ServicePolicy string `json:"servicePolicy,omitempty"`

	// Specifies the VLAN for which you are setting a self IP address. This setting must be provided when a self IP is created.
	Vlan string `json:"vlan,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
