/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetRouteDomain struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the flow eviction policy for the route domain to use when the connection limit is approached.
	FlowEvictionPolicy string `json:"flowEvictionPolicy,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the name of the route domain from which this route domain inherits settings. The default value is empty, which indicates no parent.
	Parent string `json:"parent,omitempty"`

	// The bandwidth control policy used for traffic flow.
	BwcPolicy string `json:"bwcPolicy,omitempty"`

	// Specifies the service policy to use.
	ServicePolicy string `json:"servicePolicy,omitempty"`

	// Displays the administrative partition within which the route-domain resides.
	Partition string `json:"partition,omitempty"`

	// Specifies whether the system allows a connection to span route domains.
	Strict string `json:"strict,omitempty"`

	// Staged firewall policy.
	FwStagedPolicy string `json:"fwStagedPolicy,omitempty"`

	// Enforced firewall policy.
	FwEnforcedPolicy string `json:"fwEnforcedPolicy,omitempty"`

	// Specifies the maximum number of concurrent connections you want to allow for the route domain.
	ConnectionLimit int64 `json:"connectionLimit,omitempty"`

	// Name of the IP Intelligence (Dynamic White/Black List) policy that is attached.
	IpIntelligencePolicy string `json:"ipIntelligencePolicy,omitempty"`

	// Numerical ID of the route domain
	Id int64 `json:"id,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
