/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetDnsResolver struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies number of bytes allocated for caching. The default value is 5.5mb.
	CacheSize int64 `json:"cacheSize,omitempty"`

	// Specifies whether the resolver will issue tcp queries. The default value is yes.
	UseTcp string `json:"useTcp,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Idx float32 `json:"idx,omitempty"`

	// Specifies whether the resolver will issue IPv4 queries. The default value is yes.
	UseIpv4 string `json:"useIpv4,omitempty"`

	// Displays the administrative partition within which the DNS Resolver resides.
	Partition string `json:"partition,omitempty"`

	// Specifies whether the resolver randomizes the case of query names. The default value is yes.
	RandomizeQueryNameCase string `json:"randomizeQueryNameCase,omitempty"`

	// Specifies whether we answer queries for default zones: localhost, reverse 127.0.0.1 and ::1, and AS112 zones. The default value is no.
	AnswerDefaultZones string `json:"answerDefaultZones,omitempty"`

	// Specifies route domain used for resolver outbound traffic. The default value is the default route domain.
	RouteDomain string `json:"routeDomain,omitempty"`

	// Specifies whether the resolver will issue udp queries. The default value is yes.
	UseUdp string `json:"useUdp,omitempty"`

	Type_ string `json:"type,omitempty"`

	// Specifies whether the resolver will issue IPv6 queries. The default value is yes.
	UseIpv6 string `json:"useIpv6,omitempty"`
}
