/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetRouterAdvertisementPrefixes struct {
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Indicates the on-link flag field in the prefix information option be set to 0.
	NotOnLink bool `json:"notOnLink,omitempty"`

	// Specifies the prefix for the prefix information option.
	Prefix string `json:"prefix,omitempty"`

	// Specifies the value in seconds for the Valid Lifetime field in the prefix information option. The default is 2592000.
	ValidLifetime int64 `json:"validLifetime,omitempty"`

	// Indicates the on-link flag field in the prefix information option be set to 1. This is the default.
	OnLink bool `json:"onLink,omitempty"`

	// Indicates the Autonomous Flag field in the prefix information option be set to 1. This is the default.
	Autonomous bool `json:"autonomous,omitempty"`

	// Specifies the value in seconds for the Preferred Lifetime field in the prefix information option. The default is 604800.
	PreferredLifetime int64 `json:"preferredLifetime,omitempty"`

	// Specifies the length of the prefix for the prefix information option.
	PrefixLength int64 `json:"prefixLength,omitempty"`

	// Indicates the Autonomous Flag field in the prefix information option be set to 0.
	NotAutonomous bool `json:"notAutonomous,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
