/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type NetTunnelsMap struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Rule IPv6 prefix in CIDR notation for MAP domain CE (Customer Edge) devices. The default prefix length is 48.
	Ip6Prefix string `json:"ip6Prefix,omitempty"`

	// Displays the admin-partition within which this component resides.
	Partition string `json:"partition,omitempty"`

	// Specifies port offset bits length of the MAP domain. The default is 6.
	PortOffset int64 `json:"portOffset,omitempty"`

	// Specifies EA (Embedded Address) length of the MAP domain. The default is 32 (IPv4 prefix 24 bits + PSID 8 bits).
	EaBitsLength int64 `json:"eaBitsLength,omitempty"`

	// The profile from which to inherit settings. The default value is map.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Rule IPv4 prefix in CIDR notation for MAP domain CE (Customer Edge) devices. The default prefix length is 8.
	Ip4Prefix string `json:"ip4Prefix,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
