/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type Persistence struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Virtual server SIP persistence profile configuration
	Sip string `json:"sip,omitempty"`

	// Virtual server Hash persistence profile configuration
	Hash string `json:"hash,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Displays or delete records in the persistence table.
	PersistRecords string `json:"persistRecords,omitempty"`

	// Virtual server Universal persistence profile configuration
	Universal string `json:"universal,omitempty"`

	// Virtual server Source Address persistence profile configuration
	SourceAddr string `json:"sourceAddr,omitempty"`

	// Global settings for persistence
	GlobalSettings string `json:"globalSettings,omitempty"`

	// Virtual server SSL persistence profile configuration
	Ssl string `json:"ssl,omitempty"`

	// Virtual server Cookie persistence profile
	Cookie string `json:"cookie,omitempty"`

	// Virtual server Destination Address Affinity persistence profile configuration
	DestAddr string `json:"destAddr,omitempty"`

	// Virtual server Microsoft Remote Desktop (MSRDP) persistence profile configuration
	Msrdp string `json:"msrdp,omitempty"`
}
