/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type Profile struct {

	// Virtual server Diameter traffic profile configuration
	Diameter string `json:"diameter,omitempty"`

	// LSN Pool PCP configuration profile
	Pcp string `json:"pcp,omitempty"`

	// Virtual server FastL4 traffic profile configuration
	Fastl4 string `json:"fastl4,omitempty"`

	// OCSP Stapling Parameters for clientssl profiles. This object should be associated with a cert-key-chain object in a clientssl profile.
	OcspStaplingParams string `json:"ocspStaplingParams,omitempty"`

	// Virtual server classification profile configuration
	Classification string `json:"classification,omitempty"`

	// Virtual server Rewrite profile configuration
	Rewrite string `json:"rewrite,omitempty"`

	// Virtual server Certificate Authority profile configuration.
	CertificateAuthority string `json:"certificateAuthority,omitempty"`

	// Virtual server RTSP traffic profile configuration
	Rtsp string `json:"rtsp,omitempty"`

	// Virtual server SMTP profile configuration
	Smtp string `json:"smtp,omitempty"`

	// Virtual server SOCKS traffic profile configuration
	Socks string `json:"socks,omitempty"`

	// Virtual server analytics profile configuration
	Analytics string `json:"analytics,omitempty"`

	// Virtual server Quality of Experience profile configuration
	Qoe string `json:"qoe,omitempty"`

	// Virtual server OneConnect profile configuration
	OneConnect string `json:"oneConnect,omitempty"`

	// Virtual server server-side proxy SSL profile configuration
	ServerSsl string `json:"serverSsl,omitempty"`

	// High-speed logging settings for the DNS profile.
	DnsLogging string `json:"dnsLogging,omitempty"`

	// Virtual server Server LDAP traffic profile configuration
	ServerLdap string `json:"serverLdap,omitempty"`

	Ramcache string `json:"ramcache,omitempty"`

	// Virtual server XML configuration
	Xml string `json:"xml,omitempty"`

	// Virtual server FTP traffic profile configuration
	Ftp string `json:"ftp,omitempty"`

	// Virtual server MSSQL profile configuration
	Mssql string `json:"mssql,omitempty"`

	// Virtual server SIP traffic profile configuration
	Sip string `json:"sip,omitempty"`

	// Virtual server Stream traffic profile configuration
	Stream string `json:"stream,omitempty"`

	// Virtual server Financial Information eXchange(FIX) profile configuration
	Fix string `json:"fix,omitempty"`

	// Virtual server IPOTHER for non-TCP and non-UDP traffic profile configuration
	Ipother string `json:"ipother,omitempty"`

	// Virtual server Web Acceleration profile configuration
	WebAcceleration string `json:"webAcceleration,omitempty"`

	// MBLB profile configuration (experimental)
	Mblb string `json:"mblb,omitempty"`

	// Virtual server GTP traffic profile configuration
	Gtp string `json:"gtp,omitempty"`

	// Virtual server HTML profile configuration
	Html string `json:"html,omitempty"`

	// Virtual server request logging profile configuration
	RequestLog string `json:"requestLog,omitempty"`

	// Virtual server DNS traffic profile configuration
	Dns string `json:"dns,omitempty"`

	// Virtual server Fast HTTP traffic profile configuration
	Fasthttp string `json:"fasthttp,omitempty"`

	// Virtual server SCTP traffic profile configuration
	Sctp string `json:"sctp,omitempty"`

	// Virtual server IIOP traffic profile configuration
	Iiop string `json:"iiop,omitempty"`

	// Virtual server HTTP compression profile configuration
	HttpCompression string `json:"httpCompression,omitempty"`

	// Virtual server UDP traffic profile configuration
	Udp string `json:"udp,omitempty"`

	// Virtual server HTTP traffic profile configuration
	Http string `json:"http,omitempty"`

	// Virtual server Point to Point Tunneling Protocol (PPTP) profile configuration.
	Pptp string `json:"pptp,omitempty"`

	// Virtual server Internet Content Adaptation Protocol (ICAP) profile configuration
	Icap string `json:"icap,omitempty"`

	// Virtual server custom statistics configuration
	Statistics string `json:"statistics,omitempty"`

	// Virtual server TCP traffic profile configuration
	Tcp string `json:"tcp,omitempty"`

	// Virtual server Client LDAP traffic profile configuration
	ClientLdap string `json:"clientLdap,omitempty"`

	// Virtual server HTTP response adaptation profile configuration
	ResponseAdapt string `json:"responseAdapt,omitempty"`

	// Virtual server client-side proxy SSL profile configuration
	ClientSsl string `json:"clientSsl,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Virtual server Web Security profile configuration
	WebSecurity string `json:"webSecurity,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Virtual server SPDY traffic profile configuration
	Spdy string `json:"spdy,omitempty"`

	// Virtual server NT Lan Manager profile configuration
	Ntlm string `json:"ntlm,omitempty"`

	// Virtual server SMTPs traffic profile configuration
	Smtps string `json:"smtps,omitempty"`

	// Dynamic Host Configuration Protocol, DHCPv4, profile to manage DHCPv4 network traffic.
	Dhcpv4 string `json:"dhcpv4,omitempty"`

	// Dynamic Host Configuration Protocol, DHCPv6, profile to manage DHCPv6 network traffic.
	Dhcpv6 string `json:"dhcpv6,omitempty"`

	// Virtual server HTTP/2 traffic profile configuration
	Http2 string `json:"http2,omitempty"`

	// Virtual server Radius traffic profile configuration
	Radius string `json:"radius,omitempty"`

	// Virtual server TFTP traffic profile configuration
	Tftp string `json:"tftp,omitempty"`

	// Virtual server HTTP request adaptation profile configuration
	RequestAdapt string `json:"requestAdapt,omitempty"`

	WaCache string `json:"waCache,omitempty"`
}
