/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type ProfileMssql struct {

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the pool of MS SQL database servers to which the system sends ready-only requests.
	ReadPool string `json:"readPool,omitempty"`

	// Specifies the administrative partition within which the profile resides.
	Partition string `json:"partition,omitempty"`

	// When enabled, the system decides which pool to send the client requests to by user name.
	ReadWriteSplitByUser string `json:"readWriteSplitByUser,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the users who have read-only access to the MS SQL if user-can-write-by-default is true, or the users who have write access to the MS SQL database if user-can-write-by-default is false.
	UserList string `json:"userList,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies whether users have write access by default. When set to true, all users have write access, except those added to the users list
	UserCanWriteByDefault string `json:"userCanWriteByDefault,omitempty"`

	// When enabled, the system decides which pool to send the client requests to by the content in the message.
	ReadWriteSplitByCommand string `json:"readWriteSplitByCommand,omitempty"`

	// Specifies the pool of MS SQL database servers to which the system sends requests that are not read-only
	WritePool string `json:"writePool,omitempty"`

	// Specify how many minimum time in milliseconds the connection will be persisted to write-pool after connection switch to write pool.
	WritePersistTimer int64 `json:"writePersistTimer,omitempty"`
}
