/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type ProfileHttpExplicitProxy struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the error message that will be returned to the browser when a proxy request can't be completed because of a failure to resolve the hostname in the request.
	DnsErrorMessage string `json:"dnsErrorMessage,omitempty"`

	// Specifies the error message that will be returned to the browser when a proxy request can't be completed because the request was malformed.
	BadRequestMessage string `json:"badRequestMessage,omitempty"`

	// Specifies the error message that will be returned to the browser when a proxy request can't be completed because the response was malformed.
	BadResponseMessage string `json:"badResponseMessage,omitempty"`

	// Specifies the dns-resolver object that will be used to resolve hostnames in proxy requests.
	DnsResolver string `json:"dnsResolver,omitempty"`

	// Specifies the tunnel that will be used for outbound proxy requests.  This enables other virtual servers to receive connections initiated by the proxy service.
	TunnelName string `json:"tunnelName,omitempty"`

	// Specifies the which host names are to be treated as local. Proxy requests made for those hosts will be treated as regular HTTP requests and will be sent to the configured default pool.
	HostNames string `json:"hostNames,omitempty"`

	// Specifies the behavior of the proxy service for CONNECT requests. If set to 'deny', CONNECT requests will only be honored if there is another virtual server listening for the requested outbound connection. If set to 'allow' outbound connections will be made regardless of other virtual servers.
	DefaultConnectHandling string `json:"defaultConnectHandling,omitempty"`

	// Specifies the route-domain that will be used for outbound proxy requests.
	RouteDomain string `json:"routeDomain,omitempty"`

	// Specifies the error message that will be returned to the browser when a proxy request can't be completed because of a failure to establish the outbound connection.
	ConnectErrorMessage string `json:"connectErrorMessage,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
