/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type ProfileSctp struct {

	// Specifies the number of seconds to wait before sending a heartbeat chunk. The default value is 30 seconds.
	HeartbeatInterval int64 `json:"heartbeatInterval,omitempty"`

	// Specifies the number of inbound streams. The default value is 2.
	InStreams int64 `json:"inStreams,omitempty"`

	// Specifies the maximum number of retries to establish a connection. The default value is 4.
	InitMaxRetries int64 `json:"initMaxRetries,omitempty"`

	// Specifies how many seconds the cookie is valid. The default value is 60 seconds.
	CookieExpiration int64 `json:"cookieExpiration,omitempty"`

	// Specifies the link quality of service set in sent packets. The default value is 0.
	LinkQos string `json:"linkQos,omitempty"`

	// Specifies the size (in chunks) of the rx_chunk buffer. The default value is 256.
	ReceiveChunks int64 `json:"receiveChunks,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the size (in chunks) of the tx_chunk buffer. The default value is 256.
	TransmitChunks int64 `json:"transmitChunks,omitempty"`

	// When enabled, the system delivers messages to the application layer in order. The default value is enabled.
	ReceiveOrdered string `json:"receiveOrdered,omitempty"`

	// When enabled, the default, the system accepts partial application data.
	SendPartial string `json:"sendPartial,omitempty"`

	// Specifies the internal secret string that the system uses for HTTP Message Authenticated Code (HMAC) cookies.
	Secret string `json:"secret,omitempty"`

	// Specifies the maximum number of heartbeat packets sent in a single burst.The default value is 1.
	HeartbeatMaxBurst int64 `json:"heartbeatMaxBurst,omitempty"`

	MaxPathRetransmitLimit int64 `json:"maxPathRetransmitLimit,omitempty"`

	// Specifies the maximum number of data packets sent in a single burst.The default value is 4.
	MaxBurst int64 `json:"maxBurst,omitempty"`

	// Specifies the size (in bytes) of the receive window. Prorate this value to the Receive Chunks value. The default value is 65536.
	ReceiveWindowSize int64 `json:"receiveWindowSize,omitempty"`

	// The application service to which the object belongs.
	AppService string `json:"appService,omitempty"`

	ClientSideMultihoming string `json:"clientSideMultihoming,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the size in bytes of the buffer. The default value is 65536.
	SendBufferSize int64 `json:"sendBufferSize,omitempty"`

	MaxCommunicationPaths int64 `json:"maxCommunicationPaths,omitempty"`

	// When enabled, the default, the system emulates the closing of a TCP connection.
	TcpShutdown string `json:"tcpShutdown,omitempty"`

	// Specifies the proxy buffer level after which the system opens the receive window. The default value is 4096.
	ProxyBufferLow int64 `json:"proxyBufferLow,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	ServerSideMultihoming string `json:"serverSideMultihoming,omitempty"`

	// Specifies the type of IP service set in packets sent to peer. The default value is 0.
	IpTos string `json:"ipTos,omitempty"`

	// Specifies the proxy buffer level after which the system closes the receive window. The default value is 16384.
	ProxyBufferHigh int64 `json:"proxyBufferHigh,omitempty"`

	// Displays the administrative partition within which this profile resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the number of seconds without traffic before a connection is eligible for deletion. The default value is 300 seconds.
	IdleTimeout int64 `json:"idleTimeout,omitempty"`

	// When enabled, the default, the system resets a connection when the connection times out.
	ResetOnTimeout string `json:"resetOnTimeout,omitempty"`

	// Specifies the number of outbound streams. The default value is 2.
	OutStreams int64 `json:"outStreams,omitempty"`

	// Specifies the maximum number of times the system tries again to send data. The default value is 8.
	SendMaxRetries int64 `json:"sendMaxRetries,omitempty"`
}
