/* 
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. Only LTM is included, and most endpoints are untested.
 *
 * OpenAPI spec version: 12.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

type ProfileIcap struct {

	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Specifies the ICAP URI to use in the ICAP header. Please refer to RFC 3507 section 4.2
	Uri string `json:"uri,omitempty"`

	// Specifies the host attribute to use the in the ICAP header. Please refer to RFC 3507 section 4.3.2
	Host string `json:"host,omitempty"`

	// Specifies the referrer attribute to use in the ICAP header. Please refer to RFC 3507 section 4.3.2
	Referer string `json:"referer,omitempty"`

	// Specifies the profile that you want to use as the parent profile. Your new profile inherits all settings and values from the parent profile specified.
	DefaultsFrom string `json:"defaultsFrom,omitempty"`

	// Specifies the user-agent attribute to use in the ICAP header. Please refer to RFC 3507 section 4.3.2
	UserAgent string `json:"userAgent,omitempty"`

	// Specifies the header-from attribute to use in the ICAP header. Please refer to RFC 3507 section 4.3.2
	HeaderFrom string `json:"headerFrom,omitempty"`

	// Specifies the ICAP data preview size. Please refer to RFC 3507 section 4.5
	PreviewLength int64 `json:"previewLength,omitempty"`
}
