/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysLtcfgClassFields struct {
	AppService string `json:"appService,omitempty"`

	Configsyncd string `json:"configsyncd,omitempty"`

	TmDefault string `json:"tmDefault,omitempty"`

	Appdata string `json:"appdata,omitempty"`

	Sweep string `json:"sweep,omitempty"`

	GuiHints string `json:"guiHints,omitempty"`

	Clustered string `json:"clustered,omitempty"`

	TypeInfo string `json:"typeInfo,omitempty"`

	IcontrolHints string `json:"icontrolHints,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Dbvar string `json:"dbvar,omitempty"`

	Required string `json:"required,omitempty"`

	ConfigLevel string `json:"configLevel,omitempty"`

	ClassName string `json:"className,omitempty"`

	CliHints string `json:"cliHints,omitempty"`

	Hidden string `json:"hidden,omitempty"`

	Type_ string `json:"type,omitempty"`
}
