/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysStateMirroring struct {

	// Specifies the primary self-IP address on this unit to which the peer unit in this redundant pair mirrors its connections.  This is a required setting.
	Addr string `json:"addr,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the primary self-IP address on the peer unit to which this unit mirrors its connections. This is a required setting.
	PeerAddr string `json:"peerAddr,omitempty"`

	// Specifies another self-IP address on this unit to which the peer unit mirrors its connections when the primary address is unavail able.
	SecondaryAddr string `json:"secondaryAddr,omitempty"`

	// Specifies another self-IP address on the peer unit to which this unit mirrors its connections when the primary peer address is unavailable.
	SecondaryPeerAddr string `json:"secondaryPeerAddr,omitempty"`

	// Enables or disables connection mirroring. The default is enabled.
	State string `json:"state,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
