/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysFolder struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Associate this folder with a device failover group or device sync group. 'default' to associate this folder with its parent's device group. 'non-default' to leave this field's value untouched but disassociate this folder from its parent.
	DeviceGroup string `json:"deviceGroup,omitempty"`

	// User-defined description of the folder
	Description string `json:"description,omitempty"`

	// Associate this folder with a network failover group. 'default' to associate this folder with its parent's device group. 'non-default' to leave this field's value untouched but disassociate this folder from its parent.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// Specifies whether strict device group reference validation is performed during sync behavior on items in this folder
	NoRefCheck string `json:"noRefCheck,omitempty"`

	// Read-only. Shows whether this folder will automatically remain with the same device-group as its parent folder. Use 'device-group default' or 'device-group non-default' to set this.
	InheritedDevicegroup string `json:"inheritedDevicegroup,omitempty"`

	// Specifies if this folder will be hidden.  If set to 'true', this folder will be hidden from standard command usage.  Administrators can display, modify or remove hidden folders using the '-hidden' option.
	Hidden string `json:"hidden,omitempty"`

	// Read-only. Shows whether this folder will automatically remain with the same traffic-group as its parent folder. Use 'traffic-group default' or 'traffic-group non-default' to set this.
	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
