/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSnmpCommunities struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Limits this community string's access to a portion of the oid tree.
	OidSubset string `json:"oidSubset,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Community's access level (read-only or read-write).
	Access string `json:"access,omitempty"`

	// Limits use of this community string to specific source addresses.
	Source string `json:"source,omitempty"`

	// Enables or disables the use of IPv6 in conjunction with this community.
	Ipv6 string `json:"ipv6,omitempty"`

	// The name of the community-string.
	CommunityName string `json:"communityName,omitempty"`
}
