/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysCluster struct {

	// Specifies the minimum number of cluster members that must be up for the cluster to remain Active. The default value is 0 (zero).
	MinUpMembers int64 `json:"minUpMembers,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// When enabled, specifies that when the number of active cluster members is below the value of the min up members option, the cluster fails over to its peer. Enable this parameter when you configure a redundant pair. The default value is disabled.
	MinUpMembersEnabled string `json:"minUpMembersEnabled,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the IP address of the cluster.
	Address string `json:"address,omitempty"`
}
