/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysFileSslCert struct {

	// Specifies a text expiration for the certificate.
	ExpirationString string `json:"expirationString,omitempty"`

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Specifies the user by which this file object was created.
	CreatedBy string `json:"createdBy,omitempty"`

	// Specifies the time at which this file object was last updated.
	LastUpdateTime string `json:"lastUpdateTime,omitempty"`

	// Specifies the location (URI) from where the file will be copied.
	SourcePath string `json:"sourcePath,omitempty"`

	// Path of the file in file-store.
	CachePath string `json:"cachePath,omitempty"`

	// Specifies the key-size of the key associated with this certificate in bits.
	CertificateKeySize int64 `json:"certificateKeySize,omitempty"`

	// Specifies X509 information of the certificate's subject.
	Subject string `json:"subject,omitempty"`

	// Specifies the expiration date of the certificate.
	ExpirationDate float32 `json:"expirationDate,omitempty"`

	// Specifies the standard X.509 extension as shown in RFC 2459.
	SubjectAlternativeName string `json:"subjectAlternativeName,omitempty"`

	// Specifies the user by which this file object was last updated.
	UpdatedBy string `json:"updatedBy,omitempty"`

	// Specifies the time at which this file object was created.
	CreateTime string `json:"createTime,omitempty"`

	// Specifies X509 information of the certificate's issuer.
	Issuer string `json:"issuer,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Path of the file in system outside file-store.
	SystemPath string `json:"systemPath,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	CertificateKeyCurveName string `json:"certificateKeyCurveName,omitempty"`

	IsDynamic string `json:"isDynamic,omitempty"`

	// Specifies certificate's serial number.
	SerialNumber string `json:"serialNumber,omitempty"`

	// Specifies the cryptographic fingerprint of the certificate.
	Fingerprint string `json:"fingerprint,omitempty"`

	// Specifies the certificate's version.
	Version int64 `json:"version,omitempty"`

	// Specifies the UNIX file permissions associated with the file.
	Mode int64 `json:"mode,omitempty"`

	// A checksum of the file in question.
	Checksum string `json:"checksum,omitempty"`

	// Specifies whether the file in question is a certificate bundle (contains more than 1 cert).
	IsBundle string `json:"isBundle,omitempty"`

	// Specifies the size of the file in bytes.
	Size float32 `json:"size,omitempty"`

	// Specifies the contact email address associated with the certificate.
	Email string `json:"email,omitempty"`

	KeyType string `json:"keyType,omitempty"`

	// Current revision of the file. The revision starts with 1 and gets incremented on each update.
	Revision int64 `json:"revision,omitempty"`
}
