/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSyslog struct {

	// Specifies the lowest level of system messages to include in the system log. The default value is notice.
	MessagesFrom string `json:"messagesFrom,omitempty"`

	// Specifies the lowest level of maillog messages to include in the system log. The default value is notice.
	MailFrom string `json:"mailFrom,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the lowest level of messages about daemon performance to include in the system log. The default value is notice.
	DaemonFrom string `json:"daemonFrom,omitempty"`

	// Specifies the lowest level of security/authorization messages to include in the log. The default value is notice.
	AuthPrivFrom string `json:"authPrivFrom,omitempty"`

	// Specifies the highest level of system messages to include in the system log. The default value is warning.
	MessagesTo string `json:"messagesTo,omitempty"`

	ClusteredMessageSlot string `json:"clusteredMessageSlot,omitempty"`

	// Specifies the highest level of messages about daemon performance to include in the system log. The default value is emerg.
	DaemonTo string `json:"daemonTo,omitempty"`

	// Specifies the highest level of messages about time-based scheduling to include in the system log. The default value is emerg.
	CronTo string `json:"cronTo,omitempty"`

	// Specifies the highest level of user account messages to include in the system log. The default value is emerg.
	UserLogTo string `json:"userLogTo,omitempty"`

	// Specifies the lowest level of messages about time-based scheduling to include in the system log. The default value is warning.
	CronFrom string `json:"cronFrom,omitempty"`

	// Specifies the lowest level of user account messages to include in the system log. The default value is notice.
	UserLogFrom string `json:"userLogFrom,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the lowest error level for messages from the local6 facility to include in the log. The default value is notice.
	Local6From string `json:"local6From,omitempty"`

	// Specifies the highest level of security/authorization messages to include in the log. The default value is emerg.
	AuthPrivTo string `json:"authPrivTo,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies whether or not to log messages of level emerg to the console.
	ConsoleLog string `json:"consoleLog,omitempty"`

	// Specifies the highest error level for messages from the local6 facility to include in the log. The default value is emerg.
	Local6To string `json:"local6To,omitempty"`

	// Specifies the highest level of kernel messages to include in the system log. The default value is emerg.
	KernTo string `json:"kernTo,omitempty"`

	// Specifies the lowest level of kernel messages to include in the system log. The default value is notice.
	KernFrom string `json:"kernFrom,omitempty"`

	ClusteredHostSlot string `json:"clusteredHostSlot,omitempty"`

	// Enables or disables the ISO date format for messages in the log files. The default value is disabled.
	IsoDate string `json:"isoDate,omitempty"`

	// Warning: Do not use this parameter without assistance from the F5 Technical Support team. The system does not validate the commands issued using the include parameter. If you use this parameter incorrectly, you put the functionality of the system at risk.
	Include string `json:"include,omitempty"`

	// Specifies the highest level of maillog messages to include in the system log. The default value is emerg.
	MailTo string `json:"mailTo,omitempty"`
}
