/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysPerformance struct {
	Dnsexpress string `json:"dnsexpress,omitempty"`

	// View or reset all available performance statistics
	AllStats string `json:"allStats,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// View DNSSEC signing request/response rate statistics
	Dnssec string `json:"dnssec,omitempty"`

	// View GTM request/response rate statistics
	Gtm string `json:"gtm,omitempty"`

	// View system CPU and memory usage
	System string `json:"system,omitempty"`

	// View active connection statistics
	Connections string `json:"connections,omitempty"`

	// View throughput statistics and SSL transactions/sec
	Throughput string `json:"throughput,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// View RAM Cache utilization
	Ramcache string `json:"ramcache,omitempty"`
}
