/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSflowReceiver struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Displays the administrative partition within which this receiver resides.
	Partition string `json:"partition,omitempty"`

	// Specifies the state of the receiver. The sFlow samples will be collected and sent to the receiver when enabled. The default value is disabled.
	State string `json:"state,omitempty"`

	// Specifies the maximum size of sFlow datagram. The default value is 1400.
	MaxDatagramSize int64 `json:"maxDatagramSize,omitempty"`

	// Specifies the IP address of the receiver.
	Address string `json:"address,omitempty"`

	// Specifies the IP port of the receiver. The default value is 6343.
	Port int64 `json:"port,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
