/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSoftwareImage struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Set to 'yes' if the image is an authentic image.
	Verified string `json:"verified,omitempty"`

	// The date the image was built on.
	BuildDate string `json:"buildDate,omitempty"`

	// The checksum of the image. Used to verify image integrity.
	Checksum string `json:"checksum,omitempty"`

	// The F5 product this image contains.
	Product string `json:"product,omitempty"`

	// Specifies where the image will be installed.
	Volume string `json:"volume,omitempty"`

	// The dotted version of the product.
	Version string `json:"version,omitempty"`

	// The size of the file in megabytes.
	FileSize string `json:"fileSize,omitempty"`

	// The date the file was last modified.
	LastModified string `json:"lastModified,omitempty"`

	// The image build number.
	Build string `json:"build,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
