/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysDatastor struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the percentage of full cache below which pruning stops.
	LowWaterMark int64 `json:"lowWaterMark,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies the percentage of full cache above which pruning starts.
	HighWaterMark int64 `json:"highWaterMark,omitempty"`

	// Displays the amount of space for each disk path specified.
	StoreSize int64 `json:"storeSize,omitempty"`

	// Specifies the relative weight of the web cache.
	WebCacheWeight int64 `json:"webCacheWeight,omitempty"`

	// Displays the size of the data storage in megabytes (MB).
	CacheSize int64 `json:"cacheSize,omitempty"`

	// Enables or disables the use of the disk for data storage.
	Disk string `json:"disk,omitempty"`

	// Specifies the relative weight of the dedup cache.
	DedupCacheWeight int64 `json:"dedupCacheWeight,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
