/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysApplicationService struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Displays the administrative partition within which the application resides.
	Partition string `json:"partition,omitempty"`

	// The name of the device group that the application service is assigned to.
	DeviceGroup string `json:"deviceGroup,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Run the specified template action associated with the application.
	ExecuteAction string `json:"executeAction,omitempty"`

	// Indicates that the application template used to deploy the application has been modified. The application should be updated to make use of the latest changes.
	TemplateModified string `json:"templateModified,omitempty"`

	// The name of the traffic group that the application service is assigned to.
	TrafficGroup string `json:"trafficGroup,omitempty"`

	// Read-only. Shows whether the application folder will automatically remain with the same device-group as its parent folder. Use 'device-group default' or 'device-group non-default' to set this.
	InheritedDevicegroup string `json:"inheritedDevicegroup,omitempty"`

	// Indicates any missing prerequisites associated with the template that defines this application.
	TemplatePrerequisiteErrors string `json:"templatePrerequisiteErrors,omitempty"`

	// The template defines the configuration for the application. This may be changed after the application has been created to move the application to a new template.
	Template string `json:"template,omitempty"`

	// Read-only. Shows whether the application folder will automatically remain with the same traffic-group as its parent folder. Use 'traffic-group default' or 'traffic-group non-default' to set this.
	InheritedTrafficGroup string `json:"inheritedTrafficGroup,omitempty"`

	// Specifies whether configuration objects contained in the application may be directly modified, outside the context of the system's application management interfaces.
	StrictUpdates string `json:"strictUpdates,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
