/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysCryptoCsr struct {

	// Specifies the key to use for certificate signing request generation.
	Key string `json:"key,omitempty"`

	// Specifies the x509 city to be associated with this CSR.
	City string `json:"city,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Specifies the 2 letter x509 country code to be associated with this CSR.
	Country string `json:"country,omitempty"`

	// Specifies the x509 common name to be associated with this CSR.
	CommonName string `json:"commonName,omitempty"`

	// Specifies the x509 state to be associated with this CSR.
	State string `json:"state,omitempty"`

	// Specifies the email address to be associated with this CSR.
	EmailAddress string `json:"emailAddress,omitempty"`

	// Specifies the standard X.509 extension as shown in RFC 2459 to be associated with this CSR.
	SubjectAlternativeName string `json:"subjectAlternativeName,omitempty"`

	// Specifies the x509 organization name to be associated with this CSR.
	Organization string `json:"organization,omitempty"`

	// Specifies the organizational unit to be associated with this CSR.
	Ou string `json:"ou,omitempty"`

	// Specifies the TMOS component which will be making use of this.
	Consumer string `json:"consumer,omitempty"`

	// Specifies the PKCS#9 challenge-password to be associated with this CSR.
	ChallengePassword string `json:"challengePassword,omitempty"`
}
