/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSnmp struct {

	// User defined description.
	Description string `json:"description,omitempty"`

	// Enables or disables traps about the agent status.
	AgentTrap string `json:"agentTrap,omitempty"`

	// Configures hosts or networks from which snmpd can accept traffic. Entries go directly into hosts.allow.
	AllowedAddresses string `json:"allowedAddresses,omitempty"`

	// A list of protocol/address combinations that the agent listens for traffic on.
	AgentAddresses string `json:"agentAddresses,omitempty"`

	// Enable or disable generating traps on authentication failures
	AuthTrap string `json:"authTrap,omitempty"`

	// Specifies the contact information for the system administrator.
	SysContact string `json:"sysContact,omitempty"`

	// Enables l2forwarding statistics for specified VLANs.
	L2forwardVlan string `json:"l2forwardVlan,omitempty"`

	// Default community name used when sending traps.
	TrapCommunity string `json:"trapCommunity,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// One minute load threshold before SNMPd sends a trap.
	LoadMax1 int64 `json:"loadMax1,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Five minute load threshold before SNMPd sends a trap.
	LoadMax5 int64 `json:"loadMax5,omitempty"`

	// Source used for sending traps.
	TrapSource string `json:"trapSource,omitempty"`

	// Describes the system's physical location.
	SysLocation string `json:"sysLocation,omitempty"`

	// Sets the value of the system.sysServices.0 object.
	SysServices int64 `json:"sysServices,omitempty"`

	// Enables or disables traps about device warnings.
	BigipTraps string `json:"bigipTraps,omitempty"`

	// Adds information to the snmpd.conf file. Use with extreme caution or under the guidance of F5 support.
	Include string `json:"include,omitempty"`

	// Fifteen minute load threshold before SNMPd sends a trap.
	LoadMax15 int64 `json:"loadMax15,omitempty"`
}
