/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysIcallIstatsTrigger struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies the interval to repeat event generation while the stat matches the istats-key, in seconds.
	Repeat int64 `json:"repeat,omitempty"`

	// User defined text about the configuration item.
	Description string `json:"description,omitempty"`

	// Specifies the name of the event to be generated.
	EventName string `json:"eventName,omitempty"`

	// Minimum integer value for the statistic being monitored for the trigger to fire. The default is -2147483647.
	RangeMin int64 `json:"rangeMin,omitempty"`

	// Specifies the string of name-value pairs that define the statistic to monitor.
	IstatsKey string `json:"istatsKey,omitempty"`

	// How long the counter needs to be in range before the trigger fires, in seconds.
	Duration int64 `json:"duration,omitempty"`

	// Maximum integer value for the statistic being monitored for the trigger to fire. The default is 2147483647.
	RangeMax int64 `json:"rangeMax,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
