/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysFileExternalMonitor struct {

	// The application service that the object belongs to.
	AppService string `json:"appService,omitempty"`

	// Specifies the time at which this file object was last updated.
	LastUpdateTime string `json:"lastUpdateTime,omitempty"`

	// Specifies the location (URI) from where the file will be copied.
	SourcePath string `json:"sourcePath,omitempty"`

	// Path of the file in file-store.
	CachePath string `json:"cachePath,omitempty"`

	// Specifies the user by which this file object was created.
	CreatedBy string `json:"createdBy,omitempty"`

	// Specifies the user by which this file object was last updated.
	UpdatedBy string `json:"updatedBy,omitempty"`

	// Specifies the time at which this file object was created.
	CreateTime string `json:"createTime,omitempty"`

	// Specifies the size of the file in bytes.
	Size float32 `json:"size,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Path of the file in system outside file-store.
	SystemPath string `json:"systemPath,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// A checksum of the file in question.
	Checksum string `json:"checksum,omitempty"`

	IsDynamic string `json:"isDynamic,omitempty"`

	Partition string `json:"partition,omitempty"`

	// Specifies the UNIX file permissions associated with the file.
	Mode int64 `json:"mode,omitempty"`

	// Current revision of the file. The revision starts with 1 and gets incremented on each update.
	Revision int64 `json:"revision,omitempty"`
}
