/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysSmtpServer struct {
	AppService string `json:"appService,omitempty"`

	// The user name that the SMTP server requires when validating a user.
	Username string `json:"username,omitempty"`

	// Specifies that the SMTP server does not validate users.
	AuthenticationDisabled bool `json:"authenticationDisabled,omitempty"`

	// Specifies which type of encrypted connection the SMTP server requires in order to send mail. The default is none.
	EncryptedConnection string `json:"encryptedConnection,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// The SMTP server host name in the format of a fully qualified domain name.
	SmtpServerHostName string `json:"smtpServerHostName,omitempty"`

	Partition string `json:"partition,omitempty"`

	// The password that the SMTP server requires when validating a user, in an encrypted form.
	PasswordEncrypted string `json:"passwordEncrypted,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// The host name used in SMTP headers in the format of a fully qualified domain name. This setting does not refer to the BIG-IP system's Hostname.
	LocalHostName string `json:"localHostName,omitempty"`

	// The email address that the email is being sent from. This is the \"Reply-to\" address that the recipient sees.
	FromAddress string `json:"fromAddress,omitempty"`

	// Specifies that the SMTP server validates users before allowing them to send mail. Specify this only if the SMTP server requires authentication.
	AuthenticationEnabled bool `json:"authenticationEnabled,omitempty"`

	// Specifies the SMTP port number. The default is 25.
	SmtpServerPort int64 `json:"smtpServerPort,omitempty"`

	// The password that the SMTP server requires when validating a user.
	Password string `json:"password,omitempty"`
}
