/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysIcallHandlerPeriodic struct {
	AppService string `json:"appService,omitempty"`

	// Specifies the date and time after which no more occurrences will execute
	LastOccurrence string `json:"lastOccurrence,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined explanation of the item
	Description string `json:"description,omitempty"`

	// Specifies the handler's script to execute upon invocation
	Script string `json:"script,omitempty"`

	// Specifies the date and time of the first occurrence this handler should execute
	FirstOccurrence string `json:"firstOccurrence,omitempty"`

	// Specifies the number of seconds between each occurrence of this handler's automatic execution
	Interval int64 `json:"interval,omitempty"`

	// Manage the perpetual process by specifying active or inactive
	Status string `json:"status,omitempty"`

	// Specifies a set of name/value pairs to be passed in as data to the script for every execution
	Arguments string `json:"arguments,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
