/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysService struct {

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// Specifies to enable the services. Please note that disabled services do not run until you enable, and then start the services again.
	Enable bool `json:"enable,omitempty"`

	// Ends the services. Use this option as a last resort when services do not terminate automatically. Note that this option does not operate on the default set of services, you must specify the services that you want to end.
	Force bool `json:"force,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	// Provides a status on the pre-set memory limit of the services and how much memory each service is currently using.
	Memstat bool `json:"memstat,omitempty"`

	// Specifies to reinitialize the services or re-read the config files for the services. You must specify the services that you want to reinitialize.
	Reinit bool `json:"reinit,omitempty"`

	// Specifies to remove a service so that the service does not start at boot time or with the default service set.
	Remove bool `json:"remove,omitempty"`

	// Specifies to add a service so that the service starts at boot time, or with the default service set.
	Add bool `json:"add,omitempty"`

	// Specifies to manually disable the services. After you disable services, you must enable, and then start the services before the services run again.
	Disable bool `json:"disable,omitempty"`
}
