/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysDaemonHa struct {

	// Specifies the action to take if the daemon does not maintain its heartbeat.
	HeartbeatAction string `json:"heartbeatAction,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	// User defined description.
	Description string `json:"description,omitempty"`

	// Specifies whether the running-timeout and non-running-action properties are enabled.
	Running string `json:"running,omitempty"`

	// Specifies that action that will be taken if the daemon is not running. This is a read only property.
	NotRunningAction string `json:"notRunningAction,omitempty"`

	// Specifies the amount of time (in seconds) that must elapse before the daemon is considered to be not running. This is a read only property.
	RunningTimeout int64 `json:"runningTimeout,omitempty"`

	// Specifies whether heartbeat monitoring is enabled for the daemon. If monitoring is enabled and the daemon does not maintain its heartbeat the action specified by heartbeat-action will be taken.
	Heartbeat string `json:"heartbeat,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`
}
