/*
 * BigIP iControl REST
 *
 * REST API for F5 BigIP. List of operations is not complete, nor known to be accurate.
 *
 * OpenAPI spec version: 12.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package f5api

// This describes a message sent to or received from some operations
type SysFileDashboardViewset struct {
	AppService string `json:"appService,omitempty"`

	LastUpdateTime string `json:"lastUpdateTime,omitempty"`

	SourcePath string `json:"sourcePath,omitempty"`

	CachePath string `json:"cachePath,omitempty"`

	CreatedBy string `json:"createdBy,omitempty"`

	UpdatedBy string `json:"updatedBy,omitempty"`

	CreateTime string `json:"createTime,omitempty"`

	Size float32 `json:"size,omitempty"`

	// Kind of entity
	Kind string `json:"kind,omitempty"`

	SystemPath string `json:"systemPath,omitempty"`

	// Name of entity
	Name string `json:"name,omitempty"`

	Checksum string `json:"checksum,omitempty"`

	IsDynamic string `json:"isDynamic,omitempty"`

	Partition string `json:"partition,omitempty"`

	Mode int64 `json:"mode,omitempty"`

	Revision int64 `json:"revision,omitempty"`
}
